### ISSUE TITLE
יצירה אוטומטית של תחומים

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#100]
נשתמש כרגע בתחומים שהוגדרו לפרויקט מעלה אדומים (אייקונים בדף הבית):

1. אוכלוסייה ודמוגרפיה
2. ביטחון ותשתיות
3. בריאות ורפואה
4. דת
5. חינוך
6. כלכלה, עסקים ויזמות
7. עירייה
8. רווחה וספורט
9. תחבורה
10. תכנון עיר וגיאוגרפיה
11. תרבות ותיירות

**Comment by OriHoch** [comment]
waiting for ckan-dgp server to be deployed, there are some problems there, then I will run it for existing instances

**Comment by akariv** [comment]
From the logs:
`No module named 'operators.instance_initializer'`

You just forgot to add the line here:
https://github.com/hasadna/datacity-ckan-dgp/blob/main/Dockerfile#L12

for `instance_initializer`

@OriHoch

**Comment by OriHoch** [comment]
done, you can see the groups in test instance - https://test.datacity.org.il/
