### ISSUE TITLE
יצירה אוטומטית של ארגונים

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#101]
בתור התחלה:

1. הרשות המקומית הרלבנטית (עיריה?)

2. מדינת ישראל (פה אני מתייחס לכל המידע שנגרד מתוך דאטה.גוב ואחרים. יכול להיות שנכון יותר שזה יהיה ספק המידע הרלבנטי, למשל המשרד להגנת הסביבה או משרד הפנים וכו׳? מה דעתכם?)

cc @akariv

**Comment by OriHoch** [comment]
in #97 I added a default organization for the municipality, I think most datasets can be published under that organization. If there are other departments within the municipality (like the public library) they can have their own organization. I don't think scraped data should be under a different organization, I don't think it has any benefit to end-users. Filtering should be done using groups (תחומים)  and tags

**Comment by niryariv** [comment]
להגדיר ארגון עבור כל אחד מפריטי המידע, כדי שהמערכת תייצר אותו בזמן הייבוא

**Comment by niryariv** [comment]
looking at the CKAN API it seems that we should be able to detect Org (with name, image, url etc) from the package itself, eg: https://opendataprod.br7.org.il/api/3/action/package_show?id=83d232f0-fc41-4638-acb5-2e37b3c5c7ff

But I can't get this to work on data.gov.il. Not sure if I'm missing something or data.gov.il is blocking this or it's a different API version. @OriHoch can you take a look? If this doesn't work I'll maintain it manually in a table instead.

**Comment by OriHoch** [comment]
yes, it's possible, but I don't think that's necessarily what you want to appear in the target site. for example, the organization for the corona data in odata is "גיא זומר"

**Comment by OriHoch** [comment]
you don't need to verify this using the CKAN API, you can just access the relevant dataset and see what is the linked organization on the relevant source website

**Comment by niryariv** [comment]
> you don't need to verify this using the CKAN API, you can just access the relevant dataset and see what is the linked organization on the relevant source website

you mean scraping the html?

**Comment by OriHoch** [comment]
I will use the API

**Comment by OriHoch** [comment]
please verify for each of the automatically created datasets if the organization from the source will be relevant as-is on the target

if not, which organization to create / use for that dataset

you can see on the source dataset's website the linked organization so you can verify it

**Comment by akariv** [comment]
Generally speaking I think that we shouldn't rely on the way stuff is
organized in data.gov.il, it's quite messy there.
Better to have a single organization called 'מאגר מידע ממשלתי' at the
moment and be more specific in the future if necessary.

**Comment by niryariv** [comment]
Works for me. @OriHoch let's just hard code מאגר מידע ממשלתי for anything that comes from data.gov.il

What do you guys think we should do with the odata COVID data?

**Comment by OriHoch** [comment]
no problem, what about logo, description of this organization? you could create this organization on test instance and configure it as an example

**Comment by akariv** [comment]
https://he.wikipedia.org/wiki/%D7%A1%D7%9E%D7%9C_%D7%9E%D7%93%D7%99%D7%A0%D7%AA_%D7%99%D7%A9%D7%A8%D7%90%D7%9C#/media/%D7%A7%D7%95%D7%91%D7%A5:Emblem_of_Israel.svg

covid data is also government data (as it comes from ministry of health).
The question is always about who produced the data, not where we got it
from.

**Comment by niryariv** [comment]
https://test.datacity.org.il/organization/israel-gov

**Comment by niryariv** [comment]
closing for #138
