### ISSUE TITLE
ייבוא מידע אוטומטי

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#102]
כרגע אנחנו חושבים על המשימות הבאות:

1. חילוץ הפריטים שרלבנטים לרשות המקומית הספציפית
2. אם יש מידע גאוגרפי, המרה מרשת קורדינטות ישראל ל wgs

מאגרים ראשוניים:

אנטנות סלולריות פעילות | המשרד להגנת הסביבה | https://data.gov.il/dataset/antennaactive
אנטנות סלולריות בהקמה | המשרד להגנת הסביבה | https://data.gov.il/dataset/antenna_hakama
תחנות כיבוי אש | כבאות והצלה | https://data.gov.il/dataset/israel_fire_rescue_stations
נתוני קורונה ליישוב | מידע לעם | https://www.odata.org.il/dataset/adc425d2-7635-425d-9091-4871018f7cb8
ישיבות | המרכז למיפוי ישראל | https://data.gov.il/dataset/talmudiccollege
גני ילדים | המרכז למיפוי ישראל | https://data.gov.il/dataset/kindergarten
בתי ספר | המרכז למיפוי ישראל | https://data.gov.il/dataset/school
מגרשי חניה | המרכז למיפוי ישראל | https://data.gov.il/dataset/parkinglots

(אני מחכה עם מאגר מוסדות ציבור עד שנבדוק את הנושא המשפטי)

**Comment by OriHoch** [comment]
thanks, is this a one-time import of the data (more simple), or do we expect the data to be updated over time (more complex)?

**Comment by niryariv** [comment]
For now we can make do with a snapshot of what's in the site, we'll add an ability to auto-sync periodically later on

**Comment by OriHoch** [comment]
done, data created for new instances (from instance initialize dgp task):
* organization - https://kfar-saba.datacity.org.il/organization/muni
* groups (תחומים) - https://test.datacity.org.il/group
* packages - https://kfar-saba.datacity.org.il/dataset

geojson processing - 
* done for in a separate task which runs daily on all resources
* added two custom fields for resource which allow to specify the lat / lon column (can be seen in resource edit, e.g. - https://kfar-saba.datacity.org.il/dataset/schools/resource_edit/944f5bf6-c88a-41b2-8593-5ae8bac7852a
* If a resource has values in these 2 custom fields a geojson resource will be added which displays a map - https://kfar-saba.datacity.org.il/dataset/schools/resource/944f5bf6-c88a-41b2-8593-5ae8bac7852a

**Comment by niryariv** [comment]
go over data, verify we're ok with the way it appears on the site now
