### ISSUE TITLE
עמוד גני ילדים - יחס ניגוד מינימום בין צבע טקסט לצבע רקע בלחצן 

### ISSUE THREAD

**Issue by eilanabenish** [hasadna/datacity-k8s#106]
בלחצן  Data API
![ Data API](https://user-images.githubusercontent.com/38149556/97846565-db32bc80-1cf6-11eb-961c-a1b707852862.png)

**Comment by OriHoch** [comment]
צריך לאפיין

**Comment by niryariv** [comment]
change button background to #258340

**Comment by OriHoch** [comment]
changes will be done in resource view page, for example: https://jerusalem.datacity.org.il/dataset/cellular_antennas_hakama/resource/bbf7842b-b0da-4e69-bd00-2f2cf9e1b6f9

for the data api button displayed here:
![image](https://user-images.githubusercontent.com/1198854/112135528-8aa0fa80-8bd6-11eb-9b52-ae3e09b7836b.png)

**Comment by OriHoch** [comment]
deployed
