### ISSUE TITLE
בניית אפשרות לקבוע צד לוגו / סרגל ניווט

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#111]
כפי המשוב מכפר סבא:

![Screen Shot 2020-11-02 at 20 14 42](https://user-images.githubusercontent.com/1771/97903704-22956900-1d48-11eb-95f6-4876de820a52.png)

כדי להמנע מתחזוקת טמפלייטים שונים לרשויות שונות, הרעיון הוא להפוך את זה לאפשרות קונפיגורציה, שנוכל לשים בכל עיר כפי רצונה

**Comment by OriHoch** [comment]
updated for kfar saba - https://kfar-saba.datacity.org.il/

**Comment by niryariv** [comment]
under /settings/edit/settings

![Screen Shot 2020-11-15 at 14 33 32](https://user-images.githubusercontent.com/1771/99184991-9c1d5600-274f-11eb-879d-abc97b427e4e.png)
