### ISSUE TITLE
סתם רעיון על DataCity

### ISSUE THREAD

**Issue by oferb** [hasadna/datacity-k8s#114]
Hey,
Writing in English because I couldn't find an RTL in this editor.

@eilanabenish manyanim? 😀 Good to see you contributing to a Kubernetes repo 😆😉

I took a look at [DataCity](https://maale-adummim.datacity.org.il/) and also on this very interesting table @maryLoi  made:
https://docs.google.com/spreadsheets/d/1HU20ImjisdeqpI7n3Fyr5RpfhWOPXyQCZLOdC0LOH8k/edit#gid=0

Now, this my opinion, based on very little experience with municipalities, so take it with a grain of salt, pepper, or any condiment that you prefer 😉.

Seems to me that the DataCity offering for standardizing muni data, which is something that **might** benefit muni's in the future (better standardized IT services, entrepreneurs etc), but for sure not now. So to get benefits now, DataCity adds more stuff like a website, and panels, and more things that kind of overlap with the current muni's website, and is essentially competing with existing muni website companies.
That's why Mary's table was so interesting because if you look at it, all muni's there pretty much use about 3 companies (and Jerusalem and Tel Aviv seem to have their own solutions). So there's about ~3 CMSs on the market to consider.

So why would existing munis want to add another website they need to update and maintain?

I'd like to suggest a somewhat different approach.
* Focus on the data - the hosted data files (CKAN).
* Instead of another website, offer an embedded experience, so users won't even notice it's a different website. It's just an iframe inside the muni's existing website.
* Muni's have a pain point - CMSs tend to be annoying to update. You need to have permissions, need to know how to use the interface, it might not be a great interface, and you might not be very technical.
Instead, have them email you the file, and you do the upload. That way, you're actually making it easier for them, and these files don't get updated too frequently anyway. It's just a headache to do it, especially since for them it's not a daily task.

So, bottom line:
* Currently the strategy seems to be: building a partly overlapping website to existing muni CMS providers, and having the muni use 2 CMSs. That's adding a pain to muni's.
* Instead, focus on the data only, and provide a service to the munis where they actually get real value - they don't need to upload files anymore - they just email you and you "take care of it".
* Integrate with their existing CMS using iframe - embed their data into their existing website.

Ohh and while I'm here 😀
To give muni's another reason to actually pull their data together at a national level, make a leaderboard, where even the little ones can win (or in categories like in wreslting - "heavyweight" Tel Aviv, Jerusalem, Haifa, Rishon, Be'er Sheva, "middleweight" for Rehovot, Modiin etc).
Think of a number that represents how open a muni is, and show off the top 10 munis.
It's sort of like this standardization of energy consumption:
![image](https://user-images.githubusercontent.com/5137671/97924784-de669080-1d68-11eb-8225-720839bd6ad1.png)

That's it. Hope it helps (again, just my opinion, I come with no muni experince, so gain of salt).
Good luck!

**Comment by oferb** [comment]
After a closer look, it seems like what I thought you should do is actually pretty much where you're doing, so you can take the above as a re-reinforcement to that.

**Comment by akariv** [comment]
Thanks @oferb , good suggestions! We're indeed doing most of them 😁 but we'll consider doing the rest.
