### ISSUE TITLE
editable footer 

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#115]
We got a request from Kfar Saba (which seems like it be a common need) to add specific links to the footer. 

We need a way to do this that is maintainable when we have multiple installations. 

Some approaches I've been thinking of:

1. Add an admin-editable footer block (3 copies, he/en/ar)

2. Build in a way to add links, in preset 3 columns (user can choose column, edit URL and link text) 

3. Have a city-specific template block in the footer, editable by our devs but not part of the config UI. Have CKAN include the footer when it's working in context of a certain city.

@akariv @OriHoch Thoughts on what's the best approach?

**Comment by OriHoch** [comment]
it should be configurable, if we expect admin to be able to edit html, then easiest way will be to have a footer links html block for each language, configurable from the datacity settings

**Comment by niryariv** [comment]
I'm worried users mostly will not know how to edit HTML, and this might let them shoot themselves in the foot too easily. How about option 3 - is it reasonable to implement?

**Comment by niryariv** [comment]
let's aim for an editable MD field, if we see it's complicated go with HTML

**Comment by niryariv** [comment]
@OriHoch 

1. ל נראה שהעריכה של השדה הזה נמצאת תחת ״תחומים״ - לא נכון יותר לשים את זה תחת [הגדרות](https://kfar-saba.datacity.org.il/ckan-admin/config)?

2. שיניתי את הערכים בשדה, לא נראה שינוי בפוטר

**Comment by OriHoch** [comment]
1. this is managed the same as all other custom datacity instance settings, it will be too complicated to change it
2. which instance?

**Comment by niryariv** [comment]
https://kfar-saba.datacity.org.il/

**Comment by OriHoch** [comment]
I don't see any text in the footer fields
![image](https://user-images.githubusercontent.com/1198854/98920804-36279900-24d9-11eb-8528-af01593d2ff4.png)

**Comment by niryariv** [comment]
because I erased it.. but it works now, I probably put it in the "about" footer by mistake earlier.

The links appear sandwiched between "about" and "api". can we move about/api below, with an empty line between them and the editable footer links?
![Screen Shot 2020-11-12 at 11 31 45](https://user-images.githubusercontent.com/1771/98922037-a97dda80-24da-11eb-97a6-173c349698ad.png)

**Comment by niryariv** [comment]
@niryariv open new issue

**Comment by niryariv** [comment]
closing, continue handling in #133
