### ISSUE TITLE
בדיקת נגישות לעיצוב החדש

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#116]

**Comment by eilanabenish** [comment]
שילוב הצבעים הבעייתי שאני מזהה הוא בלחצנים המשמשים לציון או להורדת פורמטים - באקסל למשל
![ניגוד שאינו עומד בדרישות המינימום ליחס ניגוד בין צבע טקסט לצבע רקע](https://user-images.githubusercontent.com/38149556/98129525-e38b2300-1ec1-11eb-92bc-74a67f505125.png)
 
איך בדקתי?

השתמשתי בתוסף לדפדפן שנקרא Color Picker
בחרתי ב Open Eyedropper
מיקמתי את הסמן על צבע הרקע
לחצתי קליק
צבע הרקע הועתק ללוח
ניגשתי לאתר [WebAIM: Contrast Checker]( https://webaim.org/resources/contrastchecker/)
הכנסתי את צבע הרקע של [הירוק בהיר]( https://webaim.org/resources/contrastchecker/?fcolor=8EE88B&bcolor=FFFFFF) [והכחול תכלת]( https://webaim.org/resources/contrastchecker/?fcolor=0058A8&bcolor=FFFFFF) וקיבלתי תוצאות – כפי שתוכלו לראות
מוזמנים לנסות בעצמכם גם בעיצוב הזה וגם בעיצובים אחרים
