### ISSUE TITLE
עדכון אתר מעלה אדומים עם המידע האוטומטי

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#126]
לייבא את אותם מאגרים שהבאנו לאתר כפ״ס, להפעיל את אלמנט המפות

**Comment by OriHoch** [comment]
בוצע, אבל ברוב הקבצים אין נתונים עבור מעלה אדומים

**Comment by niryariv** [comment]
there seems to be some issue with the fire station map, new issue at #137
