### ISSUE TITLE
מאגרי מידע - ארגונים - תחומים

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#132]
יחד עם תחומים וארגונים - לשימוש בייבוא בעתיד

אנטנות סלולריות פעילות | מדינת ישראל | https://data.gov.il/dataset/antennaactive  | סביבה
אנטנות סלולריות בהקמה | מדינת ישראל | https://data.gov.il/dataset/antenna_hakama | סביבה
תחנות כיבוי אש | מדינת ישראל | https://data.gov.il/dataset/israel_fire_rescue_stations | בטחון ותשתיות
נתוני קורונה ליישוב | מדינת ישראל | https://www.odata.org.il/dataset/adc425d2-7635-425d-9091-4871018f7cb8 | בריאות ורפואה
ישיבות | מדינת ישראל | https://data.gov.il/dataset/talmudiccollege | חינוך
גני ילדים | מדינת ישראל | https://data.gov.il/dataset/kindergarten | חינוך
בתי ספר | מדינת ישראל | https://data.gov.il/dataset/school | חינוך
מגרשי חניה | מדינת ישראל | https://data.gov.il/dataset/parkinglots | תחבורה

**Comment by niryariv** [comment]
@OriHoch moving this to high priority, mainly for the תחומים
please make sure the changes apply to maale / rishon / jlm too

**Comment by OriHoch** [comment]
we don't support updating existing data, this is harder to do as we discussed. I think for already initialized instances it will be easiest to just update manually

**Comment by niryariv** [comment]
Would deleting everything and reimporting work? Seems quicker than updating manually

**Comment by OriHoch** [comment]
what are the changes? only the organization and the associated groups?

**Comment by OriHoch** [comment]
1. the organization מדינת ישראל does not exist, we talked about it in this task - #101 - but there it is described with a different name, please clarify what needs to be done
2. some groups are not created automatically or don't match created groups, for example - there is no group "בטחון" and there is no group "תשתיות" - there is a single group "בטחון ותשתיות", also there is no group "איכות סביבה" - please clarify which groups to attach or if you mean to create new groups / modify existing groups?

**Comment by OriHoch** [comment]
regarding changes to existing data - it will be easiest to modify manually

**Comment by niryariv** [comment]
>     1. the organization מדינת ישראל does not exist, we talked about it in this task - #101 - but there it is described with a different name, please clarify what needs to be done

True - changing to מאגר מידע ממשלתי as in https://test.datacity.org.il/organization/israel-gov

>     2. some groups are not created automatically or don't match created groups, for example - there is no group "בטחון" and there is no group "תשתיות" - there is a single group "בטחון ותשתיות", also there is no group "איכות סביבה" - please clarify which groups to attach or if you mean to create new groups / modify existing groups?

Yes, because the group taxonomy is still fluid. So, if a group exists by the name mentioned, attach to that group. if not, let the user know "Group X does not exist" so they can fix manually

**Comment by OriHoch** [comment]
this task is meant for instance initialization when the instance is just created, so there is no fluidity in the groups, only the groups created by the instance initialization script will exist

**Comment by niryariv** [comment]
The fluidity is on our side. Currently we use one set in Maale Adumin, another in Kfar Saba, and we won't have a standard until we launch few more sites and get more real world feedback. So for now it's ok if we have to manually fix a few imports, just need to know which. 

I guess there's probably some way in the CKAN UI to find items with no group, if so then no need to output "doesn't exist" in the import process.

**Comment by niryariv** [comment]
@niryariv fix list to use groups per maale adumim

**Comment by niryariv** [comment]
@OriHoch עדכנתי את הרשימה למעלה לפי התחומים הקיימים

שים לב שצריך להוסיף אליהם תחום חדש - #139
