### ISSUE TITLE
אתרים לרשל״צ ולירושלים

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#136]
צריך להקים לשתי הרשויות הנ״ל אתרים , כולל יבוא אוטומטי של מידע:

rishonlezion.datacity.org.il (שים לב לאיות :)
jerusalem.datacity.org.il

**Comment by OriHoch** [comment]
rishon lezion is ready - https://rishonlezion.datacity.org.il/

**Comment by OriHoch** [comment]
jerusalem - https://jerusalem.datacity.org.il/
