### ISSUE TITLE
Maale Adumim fire stations renders an empty map

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#137]
https://maale-adummim.datacity.org.il/dataset/fire_rescue_stations/resource/b2953bc8-c5dd-4934-bbcd-b240751bc651

![Screen Shot 2020-11-19 at 9 58 04](https://user-images.githubusercontent.com/1771/99637575-ba37ce80-2a4d-11eb-98dc-02327c8d5a0a.png)

**Comment by OriHoch** [comment]
fixed
