### ISSUE TITLE
יצירת תחומים לפי הרשימה הבאה

### ISSUE THREAD

**Issue by akariv** [hasadna/datacity-k8s#14]
"value": "municipality",
            "label": "עירייה"

            "value": "transportation",
            "label": "תחבורה"

            "value": "city_planning",
            "label": "תכנון עיר וגיאוגרפיה"

            "value": "recreation_welfare_sport",
            "label": "פנאי, רווחה וספורט"

            "value": "security_infrastructure",
            "label": "ביטחון ותשתיות"

            "value": "education",
            "label": "חינוך"

            "value": "health",
            "label": "בריאות ורפואה"

            "value": "religion",
            "label": "דת"

            "value": "culture_tourism",
            "label": "תרבות ותיירות"

            "value": "economy_business",
            "label": "כלכלה, עסקים ויזמות"

            "value": "demographics",
            "label": "אוכלוסייה ודמוגרפיה"

**Comment by maryLoi** [comment]
@akariv 
ואם העירייה לא תפרסם מאגרים בתחום מסויים, יהיו לנו תחומים ריקים?...

**Comment by maryLoi** [comment]
@OriHoch 
האם אפשר בעיריות הבאות לייצר אוטומטית סט של תחומים מוגדרים מראש?

**Comment by maryLoi** [comment]
האם רשימת ספריות היא תחת תרבות או פנאי?...

**Comment by akariv** [comment]
פנאי

מניח שאפשר להפוך תחומים מסוימים ל״פרטיים״ או פשוט להציג שאין תוצאות עבור
תחום מסוים.

אדם

**Comment by maryLoi** [comment]
@OriHoch   ההצעה של אדם אפשרית?

**Comment by OriHoch** [comment]
באיזה מקום בתצוגה מדובר? בתצוגת מסמכים בפילטור בצד ימין מוצגים רק תחומים שיש להם מסמכים

**Comment by OriHoch** [comment]
בכל מקרה, הכל אפשרי

**Comment by maryLoi** [comment]
@OriHoch 
צריך שגם בדף הבית יהיו רק תחומים שקיימים. 
מניחה שנצטרך לסדר ידנית כדי שזה יהיה סימטרי ויפה?

בדף התחומים כרגע מוצגים תחומים ללא דאטה-סטים

![image](https://user-images.githubusercontent.com/8996235/89437465-4ac4fa00-d750-11ea-84c2-5b8a64825805.png)

**Comment by OriHoch** [comment]
דף התחומים נועד גם לניהול התחומים, כך שאפשר להוסיף / לערוך / למחוק תחומים קיימים, לכן לפי דעתי כדאי ששם יוצגו כל התחומים גם אם אין בהם פריטים

**Comment by maryLoi** [comment]
@akariv 
מורידה כרגע קבוצה אחת ריקה - כי יש מספר אי זוגי שלא מסתדר יפה בעמוד הבית

**Comment by akariv** [comment]
@maryLoi איזו קבוצה?

**Comment by maryLoi** [comment]
דת

**Comment by akariv** [comment]
זה לא תלוי ברוחב המסך גם ככה?
