### ISSUE TITLE
הוספת ארגון ״מאגר מידע ממשלתי״ לראשון לציון, מעלה אדומים, ירושלים

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#141]
פרטים כאן:
https://test.datacity.org.il/organization/israel-gov

**Comment by eilanabenish** [comment]
לא מצליחה בשום אופן להתחבר למעלה אדומים עם הסיסמה - לכל השאר כן

**Comment by niryariv** [comment]
מופיע בלי האייקון. תיקנתי בראשון לציון
