### ISSUE TITLE
לסגור אתר לציבור

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#143]
Can we add HTTP Basic Auth to a specific website so it's not accessible to the public?

**Comment by OriHoch** [comment]
yes

**Comment by niryariv** [comment]
thanks. no action for now

**Comment by niryariv** [comment]
בבקשה יישם לגבי אתר כפר סבא, בהנחה שזה פחות משעה עבודה (אם יותר מזה עדכן אותי קודם בבקשה)

**Comment by OriHoch** [comment]
estimated around 5 hours of work

**Comment by niryariv** [comment]
holding for now
