### ISSUE TITLE
מימוש עיצוב חדש לפורטל

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#144]
העיצוב כאן: https://zpl.io/VKrYlJ7

1. חשוב מאד להשתדל להישאר במסגרת הגבול שהגדרנו של עד עשר שעות פיתוח

2. תתעלם בבקשה מכפתור ״התקדמו לרשות מקומית חכמה״ למטה, לא לממש כרגע

**Comment by OriHoch** [comment]
opened sub-tasks:
header - #149
homepage title / search component - #148
groups component - #150
data items component - #151
footer - #152

**Comment by OriHoch** [comment]
https://github.com/hasadna/ckanext-datacity/pull/1

**Comment by OriHoch** [comment]
done + deployed to all instances
