### ISSUE TITLE
זהוי אוטומטי של שדות קורדינטות

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#146]
if the file contains fields with the following names assume this is geodata and handle accordingly (geojson, ITM transform):

lat | lon
lat | long
latitude | longtitude
x | y
e_ord | n_ord

**Comment by OriHoch** [comment]
@niryariv  the x and y seems to have been switched in the table, I think this is the correct ordering:

lat | lon
lat | long
latitude | longtitude
y | x

how does e_ord | n_ord relate to this? which one is lat / lon?

**Comment by niryariv** [comment]
Latitude = Y = N_ORD
Longitude = X = E_ORD

**Comment by OriHoch** [comment]
fixed in https://github.com/hasadna/datacity-ckan-dgp/commit/ba132dd36dfc07b10b216e3f74b3c15399110631

**Comment by OriHoch** [comment]
I ran this on Jerusalem, and encountered a problem where multiple geojson resources were added to a package, because it processes all relevant resources, and in many cases there are both csv and xlsx resources with the same data

This can occur both for the automatic xlsx resources we generate and for cases where user manually uploads multiple formats of a file. 

We need to determine a way to prevent this.

I manually deleted all the duplicated geojson resources and disabled this feature for now.

**Comment by OriHoch** [comment]
@niryariv assigning to you, please prioritize

**Comment by niryariv** [comment]
Is there a way for us to determine / flag an auto generated file? Generally I instruct users that files in a dataset should contain the same data in various formats (TBH not sure if that's the standard practice) so we can assume a single geojson file is enough

**Comment by OriHoch** [comment]
I can identify auto-generated files, the problem is with manually uploaded files, there could be multiple resources with different data, or same data, we can't know for sure

**Comment by niryariv** [comment]
for now let's assume the data in all files is the same. so we need to (1) check if a geojson exists, and (2) if not, convert one file - preferably the CSV version

**Comment by niryariv** [comment]
> for now let's assume the data in all files is the same. so we need to (1) check if a geojson exists, and (2) if not, convert one file - preferably the CSV version

can we implement this for now?

**Comment by OriHoch** [comment]
yes, so move this issue to high priority?

**Comment by OriHoch** [comment]
done, deployed

resource updated - https://jerusalem.datacity.org.il/dataset/recycling-facilities

**Comment by niryariv** [comment]
also add POINT_X (lon) | POINT_Y (lat)

**Comment by niryariv** [comment]
להוסיף את השדות הבאים לצורך הקובץ [הזה](https://kfar-saba.datacity.org.il/dataset/ginot/resource/53b59b67-91cc-42c6-ae2e-a1aae42ad774) (מעלה צילום כי גיטהאב לא מסתדר עם שילוב עברית-אנגלית):

![Screen Shot 2021-05-05 at 13 11 07](https://user-images.githubusercontent.com/1771/117126392-5dce2e80-ada3-11eb-8a49-3b4382a481e6.png)

**Comment by niryariv** [comment]
wontfix for now
