### ISSUE TITLE
auto transform ITM to WGS84

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#147]
if a newly uploaded file has geo fields (per #146) and they are ITM fields, automatically convert them to WGS84

For now we do basic detection eg if value > 200  etc

**Comment by OriHoch** [comment]
fixed in https://github.com/hasadna/datacity-ckan-dgp/commit/ba132dd36dfc07b10b216e3f74b3c15399110631

**Comment by OriHoch** [comment]
deployed, ran on Jerusalem
