### ISSUE TITLE
design fixes: icons

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#154]
1. icon should be white (we can use the icons from zeplin, if needed I can supply svg for the others)

2. add 10px padding around icon so the text does not touch the icon box border

3. box size should be 120x120 (currently 160x160)

4. font should be 14px (currently 16px)

current:
![Screen Shot 2020-12-07 at 14 23 40](https://user-images.githubusercontent.com/1771/101350903-77bd2100-3898-11eb-9f68-8833ef4abcfa.png)
goal:
![Screen Shot 2020-12-07 at 14 21 19](https://user-images.githubusercontent.com/1771/101350919-7c81d500-3898-11eb-8eb5-a27900073620.png)

**Comment by OriHoch** [comment]
1. icons are the group image, displayed also on the group page and can be changed from the UI, e.g. https://kfar-saba.datacity.org.il/group/edit/environment
2,3,4. will fix

**Comment by niryariv** [comment]
1. I know it's the group image and changeable on the UI, the key is that we want to default images to be the correct (white) one. If I need to supply them in svg or png white let me know, but I'm looking for a solution that doesn't require manually updating all the icons of the existing sites

2. Make it 7px instead of 10px please

**Comment by OriHoch** [comment]
for existing instances it will be fastest to change manually, it will be best if you could upload the desired images for the group and check how it looks in both the homepage icons and in the individual group pages. Also need to handle the group icons for Kfar Saba which are different.

For new instances - I will modify the instance initialization task in this task - #157

**Comment by OriHoch** [comment]
design fixes done + deployed to all instances
