### ISSUE TITLE
design fixes: dataset list on homepage

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#155]
background color should be white (as on the header) 

current:
![Screen Shot 2020-12-07 at 14 34 29](https://user-images.githubusercontent.com/1771/101351641-89eb8f00-3899-11eb-92af-4906aec2d26b.png)
goal:
![Screen Shot 2020-12-07 at 14 36 54](https://user-images.githubusercontent.com/1771/101351733-b30c1f80-3899-11eb-82e8-ad6f14bc5b52.png)

**Comment by OriHoch** [comment]
will use the top header background color setting (default to white)

**Comment by OriHoch** [comment]
done + deployed on all instances
