### ISSUE TITLE
System components

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#166]
As we discussed, please create a list of various system components (CKAN/Redis/pg/etc) with versions, as well as the various cloud/hosting services we use, so we can send to clients' cyber security teams.

**Comment by OriHoch** [comment]
sent you the details

**Comment by niryariv** [comment]
Pasting here for future use:


Google Cloud - Kubernetes Cluster | 1.16
Google Cloud - PostgreSQL server | 9.6
Google Cloud - Storage | -
CKAN | 2.8.4
Redis | 6
Nginx | 1.17
Zookeeper | 3.4.10
Solr | 5.5.5
Python | 2.7

[CKAN Vulnerabilities](https://snyk.io/vuln/pip:ckan) (none)
