### ISSUE TITLE
להחזיר סרגל ניווט באתר כפ״ס למרכז, מעל ״פורטל מידע כפר סבא״

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#169]
נראה שהלוגו דוחף אותו ימינה:

<img width="1436" alt="Screen Shot 2021-01-04 at 9 57 05" src="https://user-images.githubusercontent.com/1771/103513539-7ec55800-4e73-11eb-8243-7251f8946849.png">

**Comment by OriHoch** [comment]
deployed
