### ISSUE TITLE
Jerusalem design changes

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#170]
@OriHoch for now do not implement yet, just give me two time estimates for these changes:
1. Only what we can achieve via admin settings
2. Full implementation

This is the goal:
![דטה סיטי - דף בית(1)](https://user-images.githubusercontent.com/1771/103745959-04c6d780-5009-11eb-9393-6a3fce34be1c.jpg)

background image:
![תמונת רקע](https://user-images.githubusercontent.com/1771/103745980-0a242200-5009-11eb-8f5e-c89d5e3dfdf0.png)

white logo (a bit hard to see :))
![לוגו עירייה - טקסט לבן](https://user-images.githubusercontent.com/1771/103745978-098b8b80-5009-11eb-9e6b-61f095f93ac7.png)

Font: almoni-neue-family-otf

**Comment by OriHoch** [comment]
1. Looks like all the logos, background image and colors can be changed from the admin - 1-2 hours
2. estimation for implementing all changes - 5-10 hours

**Comment by niryariv** [comment]
Please go ahead with option 1. Note we also need to change the nav bar links color (not in the sketch above)

**Comment by OriHoch** [comment]
done, mostly with our custom settings, and some using custom CSS in the ckan admin (https://jerusalem.datacity.org.il/ckan-admin/config)
