### ISSUE TITLE
קובץ גאוגרפי לא מיוצר

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#171]
בהמשך ל #168, הועלה קובץ חדש - אבל נראה שהמערכת לא מייצרת קובץ גאוג׳ייסון

https://jerusalem.datacity.org.il/dataset/recycling-facilities

**Comment by OriHoch** [comment]
the changes in issue #146 were rollbacked until we decide on a fix
I see you wrote some comments there, but issue is not high priority, do you want to move it to high priority?

**Comment by OriHoch** [comment]
closing this issue as #146 is the relevant issue
