### ISSUE TITLE
fix image / border overlap in Jerusalem

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#173]
As we discussed, add 10px or so to the top of the image to prevent this:

![Screen Shot 2021-01-11 at 10 43 11](https://user-images.githubusercontent.com/1771/104160433-cf9bfa00-53f9-11eb-9f74-5f9d218b865e.png)

**Comment by OriHoch** [comment]
the cutoff point is not constant, it depends on the browser resolution

added some white space + white background to the text

**Comment by niryariv** [comment]
Perfect. Thanks!
