### ISSUE TITLE
csv uploaded to datastore - _id column is not supported

### ISSUE THREAD

**Issue by OriHoch** [hasadna/datacity-k8s#176]
when uploading a csv to the datastore, if the csv contains a column name `_id` the data preview is not available

![image](https://user-images.githubusercontent.com/1198854/104285844-ddff1a00-54bc-11eb-9d7d-fbb668880af5.png)

**Comment by OriHoch** [comment]
@niryariv this may be hard to fix as it requires change to core CKAN functionality, I think it's easier for now just not to upload csv files with column `_id`, please prioritize

**Comment by niryariv** [comment]
Did CKAN add the _id column? I downloaded from the site in order to change x/y and then uploaded again

**Comment by OriHoch** [comment]
yes, if you download from this option it adds an `_id` column (from the main download buttons it does not)

![image](https://user-images.githubusercontent.com/1198854/104286610-f3287880-54bd-11eb-8027-773359d48ce2.png)

**Comment by niryariv** [comment]
uploaded without _id

**Comment by niryariv** [comment]
seems ok now. when does the xls/geojson conversion run?

**Comment by OriHoch** [comment]
it runs daily, but I ran it manually now

**Comment by OriHoch** [comment]
let's continue on issue #168 and keep this issue comments for the issue of `_id` column

**Comment by niryariv** [comment]
> @niryariv this may be hard to fix as it requires change to core CKAN functionality, I think it's easier for now just not to upload csv files with column `_id`, please prioritize

We'll take this approach :) Closing
