### ISSUE TITLE
edit preview of the CKAN URL

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#18]
now it's:

![image](https://user-images.githubusercontent.com/8996235/89125711-18fe2a00-d4e9-11ea-86f2-d9840884a7ff.png)

is it possible to add image?

אני מציעה שהטקסט יהיה:
"פורטל המידע הפתוח - עיריית מעלה אדומים"

**Comment by OriHoch** [comment]
the text is editable in settings - https://maale-adummim.datacity.org.il/settings/edit/settings - under site title hebrew / english / arabic (hebrew is used for the other languages if empty)

I'll add an option to add a sharing image

**Comment by OriHoch** [comment]
@maryLoi deployed

added option to set site sharing image URL, image should be a square 256px X 256px and will be used for any sharing, like whatsapp or facebook.

It can be uploaded to the datacity wordpress (media > add new) and then use the link to the image from there in the settings

I currently uploaded a square image I created from the maale adummim vertical logo
