### ISSUE TITLE
File preview error

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#180]
https://jerusalem.datacity.org.il/dataset/dogs-spots/resource/f6efaa6e-587f-4f18-9900-f4ec88d15a68#

![Screen Shot 2021-01-13 at 13 58 59](https://user-images.githubusercontent.com/1771/104449637-930e0100-55a7-11eb-851c-54663210cb84.png)

**Comment by niryariv** [comment]
I assume this is the same issue as #175 - could you elaborate on what causes this?

**Comment by OriHoch** [comment]
yes, it's the same issue, closing this one, will investigate in #175
