### ISSUE TITLE
נסיון לאיפוס ססמא גורם להודעת שגיאה

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#183]
@OriHoch בנוהל הרגיל, תן לי בבקשה הערכת זמן לפני שמתחילים לעבוד

1. פתח דף איפוס ססמא
2. הכנס כתובת מייל
3. לחץ על כפתור Request Reset
4. שגיאת Internal Server Error:

![Screen Shot 2021-01-27 at 10 46 44](https://user-images.githubusercontent.com/1771/105966301-23127700-608d-11eb-9813-ed2f2d6f84c3.png)

**Comment by OriHoch** [comment]
תוקן
