### ISSUE TITLE
שנוי צבעים לאלמנט תחומים בדף הבית

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#184]
קיים:
![Screen Shot 2021-02-01 at 16 52 43](https://user-images.githubusercontent.com/1771/106474777-e9d37000-64ad-11eb-9e28-2a8303c75343.png)

רצוי:
![image](https://user-images.githubusercontent.com/1771/106474957-1ab3a500-64ae-11eb-9a18-2d5735453b01.png)

יש לי רק את הצילום לעיל.. צבעים:
bg: #fff
text: #13699e
icon: #395d7a

**Comment by OriHoch** [comment]
@niryariv the change should be done for all sites or only Jerusalem?

**Comment by OriHoch** [comment]
done for Jerusalem, reopen if needed for all sites as well

**Comment by niryariv** [comment]
yes, please implement for all sites

**Comment by OriHoch** [comment]
deployed to all sites
