### ISSUE TITLE
ליצור דף באתר: מידע ליזם

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#185]
דף תוכן, מכיל כרגע

[קישור לקוד](https://github.com/hasadna/datacity-k8s)
[קישור ל CKAN API](https://docs.ckan.org/en/2.9/api/)

**Comment by OriHoch** [comment]
* איזה אתר?
* מה העיצוב הרצוי?
* באיזה URL?
צריך יותר פרטים..

**Comment by niryariv** [comment]
אתר datacity.org.il


>     * איזה אתר?
datacity.org.il

>     * מה העיצוב הרצוי?
עיצוב של דף סטנדרטי באתר, למשל [אודות](https://www.datacity.org.il/about/)

תמונת רקע:
![tablet-1075790_1920](https://user-images.githubusercontent.com/1771/107212148-33244200-6a0f-11eb-85f9-8cb6b398f169.jpg)

קרדיט תמונה (לא מתחייב ברשיון, רק אם יש לנו כבר מקום לשים קרדיטים כאלו)
`Image by <a href="https://pixabay.com/users/niekverlaan-80788/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1075790">Niek Verlaan</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1075790">Pixabay</a>
`

>     * באיזה URL?
datacity.org.il/entrepreneur

**Comment by niryariv** [comment]
@OriHoch 

כשהדף מוכן שלח קישור בבקשה ואכניס שם את הטקסט

**Comment by niryariv** [comment]
done, as agreed with Dorit the URL is https://www.datacity.org.il/developers/
