### ISSUE TITLE
תיקון תאימות לאקספלורר

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#188]
המשתמשים בירושלים מדווחים על רינדור בעייתי באקספלורר 11 שרץ על ווינדוס 10. 

צילום מסך:

![image](https://user-images.githubusercontent.com/1771/107870775-0e631b00-6ea4-11eb-8934-fd7d16e2a58d.png)
 
@OriHoch תן לי בבקשה הערכת זמן בלבד בשלב זה

**Comment by OriHoch** [comment]
1-3 hours

**Comment by niryariv** [comment]
מאושר ע״י דורית - מחזיר אליך לפיתוח

**Comment by OriHoch** [comment]
deployed
