### ISSUE TITLE
homepage layout

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#19]
I suggest to copy this, seems basic enough and well organized.

http://data.surrey.ca/

Another good example for banner+search box element
http://dataportal.aquacross.eu/

Better design, still basic
http://dados.ufrn.br/

Heavy design
http://data.zagreb.hr/

**Comment by maryLoi** [comment]
Ori - please check configurability of the following:

1. 
Hebrew fonts:
Arimo, Varela Round, Rubik, Assistant
https://fonts.google.com/?subset=hebrew

2. Choice of backgrounds

3. Icons

4. יתכן שחלק מהפורטלים המעוצבים פרסמו קוד פתוח של האתר?
למשל זה, הם חבים של מור
http://datamx.io/

**Comment by maryLoi** [comment]
האם אנחנו נרצה אזכור לדאטה-סיטי או לוגו בפורטלים של העיריות? או שזה
white label?

**Comment by maryLoi** [comment]
טקסט לכותרת של עמוד הבית:
ברוכים הבאים לפורטל המידע הפתוח של מעלה אדומים!
כאן תמצאו מאגרי מידע פתוחים של העיר, לשימוש חופשי של תושבים, יזמים וכל מי שמתעניינת בנעשה בעיר.

**Comment by OriHoch** [comment]
@maryLoi all options are possible, please write the required design and I'll implement

**Comment by maryLoi** [comment]
@OriHoch 
אתה יכול בבקשה לתת הערכה לגבי היקף השעות הנדרש למימוש של האופציה המורכבת יותר לעומת הפשוטה יותר, מבין שתי אלה
http://data.surrey.ca/
http://dados.ufrn.br/

**Comment by OriHoch** [comment]
קשה לתת הערכות בשעות, תכתבי מה ההעדפות והדרישות ואני אממש מה שיותר הגיוני / יעיל

**Comment by maryLoi** [comment]
mockup 

https://app.moqups.com/UbDbmfrKG5/view/page/afd1f62fd

TBD: image, icons

**Comment by maryLoi** [comment]
Configurable per city: 

all colors
city logo
Title 1 - part 2
banner image (city skyline illustration)
About page

**Comment by OriHoch** [comment]
implementation will be done in #24

**Comment by OriHoch** [comment]
done + deployed
