### ISSUE TITLE
מפה לא מוצגת בפריט מידע ספציפי

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#190]
https://kfar-saba.datacity.org.il/dataset/mazlemot/resource/a24bffa1-b7fa-4c0f-82ff-ddff62da5140

נראה שהמערכת ייצרה את קובץ הג׳יסון בלי תוכן?

אם התיקון מעל שעתיים אשר איתי קודם בבקשה

**Comment by OriHoch** [comment]
there are two possible problems there:

1. invalid lat/lon fields are set in the resource metadata, not matching any field names in the csv
![image](https://user-images.githubusercontent.com/1198854/108179176-fb538380-710d-11eb-8c72-234a37cca0bb.png)

2. looking at history, seems like the resource was editted, currently if resource is edited it is not re-processed. To ensure re-processing, need to delete the existing resource and add a new one (this also relates to current logic of only processing the first csv file, so if there are 2 it will process only 1 of them)
![image](https://user-images.githubusercontent.com/1198854/108179481-55ecdf80-710e-11eb-81c9-c252111a61f0.png)

**Comment by OriHoch** [comment]
I manually tested the current CSV and it is valid for geojson processing, so I suggest to delete the existing csv and geojson resources and create new ones

**Comment by niryariv** [comment]
@OriHoch is there a way to trigger the processing manually? (so I can keep the CSV and clear the lat/lon fields in the dataset management UI and let it run again)

**Comment by OriHoch** [comment]
you can trigger it manually from the dgp app, but the processing does not update existing resources, you have to recreate

**Comment by niryariv** [comment]
בטיפול מול הלקוח
