### ISSUE TITLE
Switch to OSM map tiles

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#195]
Specifically HOTOSM: 

http://a.tile.openstreetmap.fr/hot/${z}/${x}/${y}.png
http://b.tile.openstreetmap.fr/hot/${z}/${x}/${y}.png

replaces #122 and #194

**Comment by niryariv** [comment]
@OriHoch can you prioritize please? Important to fix this as soon as possible.

**Comment by OriHoch** [comment]
deployed
