### ISSUE TITLE
שגיאה בהעלאה למחסן נתונים

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#198]
1. דף ה[קובץ](https://kfar-saba.datacity.org.il/dataset/takziv_ragil/resource/2368a4c8-44c0-4dcc-9ec2-c3faecbe7036#) - ״תצוגה אינה זמינה״

![Screen Shot 2021-03-07 at 9 16 01](https://user-images.githubusercontent.com/1771/110232359-c032bc00-7f25-11eb-87ed-a8e4a1466fdd.png)

2. נסיון להעלאה ידנית דרך ממשק ניהול מחזיר שגיאה:
![Screen Shot 2021-03-07 at 9 16 56](https://user-images.githubusercontent.com/1771/110232370-e0627b00-7f25-11eb-8d18-163ad9f87f48.png)

**Comment by niryariv** [comment]
בנוהל הרגיל, הערכת זמן בשלב זה

**Comment by OriHoch** [comment]
xlsx files are not supported for datastore
it works on the csv file - https://kfar-saba.datacity.org.il/dataset/takziv_ragil/resource/09a2f437-c322-4aef-97f5-2ccb7be4a22d
there is no easy solution, as datastore is a core component of CKAN, so hard to make changes to it

Will require ~5-10 hours research into possible solutions

**Comment by niryariv** [comment]
המערכת לא אמורה להחזיר הודעה כמו
No preview available for this type of file
או משהו דומה, במקום הודעת שגיאה?

**Comment by OriHoch** [comment]
תיקון הודעת השגיאה המוצגת - כ3 שעות
(צריך עיצוב וטקסט ספציפי שרוצים שיוצג במקריםש בהם אין תצוגה של הנתונים)

**Comment by niryariv** [comment]
> Will require ~5-10 hours research into possible solutions
Approved.

Q: Does CKAN work with XLS files better than XLSX? Most of these files are files that we convert CSV->XSLX. We can change that to XLS if that helps (or perhaps convert only to GeoJSON where useful)

**Comment by OriHoch** [comment]
I don't know, it's possible that XLS will be better supported

**Comment by niryariv** [comment]
any results on the research?

**Comment by OriHoch** [comment]
haven't started it, issue is currently assigned to you

**Comment by OriHoch** [comment]
5-10 hours research is approved?

**Comment by niryariv** [comment]
approved

**Comment by niryariv** [comment]
@OriHoch what's the current status?

**Comment by OriHoch** [comment]
@niryariv haven't started, will try to get to it next week

**Comment by OriHoch** [comment]
this issue has a few different problems and multiple unrelated comments, I will continue work on the discussed 5-10 hours research into support of xlsx files in #229
