### ISSUE TITLE
התאמה לגלישה בנייד

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#199]
בקשות מהלקוח. תן לי בבקשה הערכת זמן פיתוח בלבד בשלב זה.

1. מירכוז הדף

![Screen Shot 2021-03-07 at 12 15 29](https://user-images.githubusercontent.com/1771/110236534-fb8db480-7f3e-11eb-9dc8-af1fe2a26f25.png)

2. לטפל בגלישת הטקסט מחוץ לקו המקיף (או להעלים את הקו בכלל בגלישה בנייד)

![Screen Shot 2021-03-07 at 12 03 40](https://user-images.githubusercontent.com/1771/110236199-2971f980-7f3d-11eb-9687-09d31cefe615.png)

3. למרכז אייקונים של תחומים

![Screen Shot 2021-03-07 at 12 03 59](https://user-images.githubusercontent.com/1771/110236223-46a6c800-7f3d-11eb-8cb9-d7e4e0805c85.png)

4. לרווח בין הטורים ובינם לצדדים
![image](https://user-images.githubusercontent.com/1771/110236737-347a5900-7f40-11eb-9119-890bf88b0b99.png)

**Comment by OriHoch** [comment]
כ-5 שעות

**Comment by niryariv** [comment]
מאושר לביצוע
cc @dorit102

**Comment by OriHoch** [comment]
deployed
