### ISSUE TITLE
domain

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#2]
change CKAN's domain to 

www.datacity.org.il/opendata

**Comment by OriHoch** [comment]
what will be displayed in this URL?

**Comment by maryLoi** [comment]
correction: it should be  
maale-adummim.datacity.org.il

the last new CKAN instance will be at this address
instead of https://ckan-cloud-maale-adummim-f7f45170267e.odata.org.il/

**Comment by OriHoch** [comment]
done

https://maale-adummim.datacity.org.il
