### ISSUE TITLE
תיקון רשימת היררכיה בנייד

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#200]
בדסקטופ:
![Screen Shot 2021-03-15 at 14 25 51](https://user-images.githubusercontent.com/1771/111153254-61f78000-859a-11eb-877b-75d6f51b77f1.png)

בנייד:
![Screen Shot 2021-03-15 at 14 20 27](https://user-images.githubusercontent.com/1771/111152972-07f6ba80-859a-11eb-9f99-90d26c5728bd.png)

לשנות את הטקסט האפור ללבן, או את הרקע של הטקסט לאפור כמו בדסקטופ

**Comment by OriHoch** [comment]
deployed
