### ISSUE TITLE
change file format tag background colors

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#202]
CSV: #8F7000
XLS: #258340
GEOJSON: #8434DA
XSL (/default): #707070

![Screen Shot 2021-03-22 at 17 23 17](https://user-images.githubusercontent.com/1771/112014157-4d376100-8b33-11eb-89c6-2f6d617c433e.png)

**Comment by OriHoch** [comment]
all file formats except csv, xls or geojson will have background #707070

**Comment by OriHoch** [comment]
deployed
