### ISSUE TITLE
change count tag bg color

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#203]
to #707070

![Screen Shot 2021-03-22 at 17 26 17](https://user-images.githubusercontent.com/1771/112014587-b7500600-8b33-11eb-9d2e-d6896d93db5d.png)

**Comment by OriHoch** [comment]
change will be done on page "פריטי מידע" for all sites, for example:
https://jerusalem.datacity.org.il/dataset

for counts displayed here:
![image](https://user-images.githubusercontent.com/1198854/112136045-22064d80-8bd7-11eb-93ad-3ec78178a513.png)

**Comment by OriHoch** [comment]
deployed
