### ISSUE TITLE
change link color

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#204]
across the site, to #3D3DFF
![Screen Shot 2021-03-22 at 17 34 39](https://user-images.githubusercontent.com/1771/112015881-e31fbb80-8b34-11eb-972a-ecc8144bdba5.png)

**Comment by OriHoch** [comment]
just the links shown in this screenshot? we have many differently styled links in the site, some have dark backgrounds and are white, and some have other designs. To change all links will be quite hard, it will be helpful to have a specific list of link colors which need to change

**Comment by niryariv** [comment]
the task refers to links as in the example, to which the CSS designates the color `#337ab7` - need to replace with with  `#3d3dff`

I couldn't a place where the background is darker than the above. Can you point to an example?

**Comment by OriHoch** [comment]
https://jerusalem.datacity.org.il/ - links in the header and footer

**Comment by OriHoch** [comment]
I will change the color of links in extra information box on dataset details and resource details pages: 

for example:

dataset page: https://jerusalem.datacity.org.il/dataset/urban-renewal-evacuation-construction
![image](https://user-images.githubusercontent.com/1198854/112314646-eab89f00-8cb1-11eb-9407-e2387694f9c3.png)


resource page: https://jerusalem.datacity.org.il/dataset/bus-stops/resource/dc6df3c8-291a-4465-80cd-201654e236e2
![image](https://user-images.githubusercontent.com/1198854/112314737-0ae85e00-8cb2-11eb-86fa-4d5a57e2aae3.png)

**Comment by OriHoch** [comment]
deployed
