### ISSUE TITLE
לעגל פינות המסגרת של הרכיב המרכזי מעל תיבת החיפוש בצפייה בנייד

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#205]
![Screen Shot 2021-04-04 at 11 28 51](https://user-images.githubusercontent.com/1771/113503195-f1a8a280-9538-11eb-98be-cffded1843dd.png)

**Comment by OriHoch** [comment]
זה יותר קשה לעשות שינויים ספציפיים לאתר בודד
האם אפשר לעשות את השינוי לכל האתרים?

**Comment by niryariv** [comment]
כן

**Comment by OriHoch** [comment]
deployed
