### ISSUE TITLE
להכניס קו מקווקו בין אלמנטים בפוטר

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#206]
במסך מלא, הפוטר מחולק לשלושה טורים. בתצוגה בנייד הם מופיעים אחד מתחת לשני. צריך להוסיף אלמנט של קו מקווקו ביניהם כדי לייצר הפרדה, עם ריווח בין הקו עצמו לטקסט שמעליו ומתחתיו (אותו רווח שקיים עכשיו בין השורות). 

 #e5e5e5 עובי הקו 2 פיקסל, צבע

![Screen Shot 2021-04-04 at 11 35 52](https://user-images.githubusercontent.com/1771/113503539-39c8c480-953b-11eb-8332-357db06ba743.png)

**Comment by OriHoch** [comment]
deployed
