### ISSUE TITLE
להגביל רוחב טורים בפוטר, להוסיף ריווח

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#207]
ספציפית לגבי הימני, שלא יוכל לקבל יותר מ %40 רוחב, למנוע מצב כזה:

להוסיף ריווח של 20 פיקסל בין הטורים
![Screen Shot 2021-04-04 at 11 51 29](https://user-images.githubusercontent.com/1771/113503805-d770c380-953c-11eb-9de3-16fe5284c10c.png)

**Comment by OriHoch** [comment]
deployed
