### ISSUE TITLE
עריכת הפוטר

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#208]
אני לא יודע איזה מהדברים הנ״ל אפשרי במסגרת המרקדאון - עדכן אותי בבקשה מה ניתן ומה יצריך פיתוח נוסף, ובאיזה היקף. 

* מסגרת אדומה סביב הפסקה של ״התאריך בכותרת שכבת המידע..״
* מסגרת לבנה סביב ״צרו קשר״ 
*   מסגרת לבנה סביב הקישור ל״אודות ירושלים״, לידו אייקון של אינפו (מצ״ב, אפשר להחליף את זה פשוט באות בבולד). ממה שאני רואה הקישור הזה לא ניתן לעריכה בממשק אדמין?
* 
![info](https://user-images.githubusercontent.com/1771/113720142-029f1280-96f7-11eb-83af-2f565cb3de21.png)

**Comment by OriHoch** [comment]
markdown does not support styling, I can change to allow html, that way you can combine html tags with the markdown, for example:

```
<div style="border: 1px solid red;">
* [this is markdown](http://www.example.com)
</div>
```

yes, the about site link is hard-coded, not part of the editable footer markdown

**Comment by niryariv** [comment]
OK, please allow HTML (is there a way to limit to certain tags?)

**Comment by OriHoch** [comment]
will be handled in #209

**Comment by OriHoch** [comment]
not easy to limit to certain tags
