### ISSUE TITLE
חירבוש שמות עמודות בעברית בויזואליזציה של מאגר

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#21]
https://maale-adummim.datacity.org.il/dataset/special-kindergardens/resource/5cf97bf7-3877-426b-821b-7a64b34d7b99

**Comment by OriHoch** [comment]
ckan/ckanext-xloader#111

**Comment by OriHoch** [comment]
fixed + deployed, new resources will be uploaded with hebrew headers

@maryLoi if there are existing resources with hebrew column names they will need to be fixed manually by editing the resource, clicking on datastore tab and then on 'העלאה למחסן הנתונים' and after a few seconds it should be updated with hebrew column names

updated for this resource:
https://maale-adummim.datacity.org.il/dataset/special-kindergardens/resource/5cf97bf7-3877-426b-821b-7a64b34d7b99
