### ISSUE TITLE
לא ניתן לצפות בקובץ שהומר לאקסל

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#218]
1. העליתי את [הקובץ הבא](https://netanya.datacity.org.il/dataset/neighborhoods/resource/f0c71601-2ac5-489b-80b8-dc15564a7b59) csv:
2. המערכת יצרה אוטומטית [קובץ אקסל](https://netanya.datacity.org.il/dataset/neighborhoods/resource/0476dbdd-9f38-4d3a-8fb4-5ecd7cad980e)
3. הורדת הקובץ מראה שהוא תקין. אבל סייר הנתונים לא מצליח להציג את התוכן:
![Screen Shot 2021-05-25 at 14 54 32](https://user-images.githubusercontent.com/1771/119493688-2121a180-bd69-11eb-81d7-320a1052578e.png)

**Comment by OriHoch** [comment]
duplicate of #198

**Comment by niryariv** [comment]
I don't understand. In #198 it was a file uploaded by the user. Here the user uploaded a CSV file and our system converted it to XLSX. 

It seems like some CSV->XLSX conversions result in [viewable files](https://jerusalem.datacity.org.il/dataset/active-cell-towers-ministry-of-environmental-protection/resource/b78f3bd8-57f1-492f-a599-1ec9b9a96813), others in error messages as in #198 and others in empty table like here. What causes the difference?

**Comment by OriHoch** [comment]
the error and estimate for research is the same as for #198 - "Will require ~5-10 hours research into possible solutions"

**Comment by niryariv** [comment]
נסגר דרך #198
