### ISSUE TITLE
תיקונים לירושלים

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#219]
כרגיל תן לי קודם הערכת שעות בבקשה

- [ ] הורדת אלמנט ״מס׳ עוקבים״ מדף פריט
- [ ] מירכוז לוגו ארגון בדף פריט
- [ ] ביטול שינוי צבע טקסט בזמן הובר על קישור (כרגע משנה ללבן. עדכן אותי אם זה משהו שאני יכול לעשות דרך ממשק אדמין)
- [ ] שינוי צבע מסגרת של כפתור ״לכל מאגרי המידע״ ללבן
- [ ] שינוי רקע כפתור ״לכל מאגרי המידע״ בזמן הובר לצבע
 #1a8aae
- [ ] כנ״ל לרקע כפתורי התחומים 
![image](https://user-images.githubusercontent.com/1771/119654441-22b69c80-be31-11eb-8c59-78c3bfeb6f0a.png)

![image](https://user-images.githubusercontent.com/1771/119662043-9a88c500-be39-11eb-8a7f-5592bf2725bb.png)
![Screen Shot 2021-05-26 at 15 50 56](https://user-images.githubusercontent.com/1771/119662533-2b5fa080-be3a-11eb-9db4-6e3b51bc3621.png)

**Comment by OriHoch** [comment]
we should not make site-specific changes, please specify for each change if it should be global or controlled per-site via settings

**Comment by OriHoch** [comment]
please specify for each change which page and component it is referring to

**Comment by niryariv** [comment]
להלן גרסה מעודכנת

שינוי | באיזה מקום? | בכל האתרים?
-- | -- | --
לא להציג אלמנט ״מס׳ עוקבים״ | פריט מידע, ארגון, תחום, וכל מקום אחר שהוא מופיע | כן
מירכוז לוגו ארגון | פריט מידע, ארגון, וכל מקום אחר שהוא מופיע בטור הימני לצד התוכן המרכזי | כן
ביטול שינוי צבע טקסט של קישור בזמן הובר על קישור. להמיר בקו תחתון | כל מקום שמוגדר בו הובר לבן | כן (ככל שאני רואה ההובר הלבן קיים רק בירושלים)
שינוי רקע כפתור ״לכל מאגרי המידע״ בזמן הובר לצבע #d7d7d7 | דף בית | כן
שינוי רקע כפתורי תחומים בזמן הובר לצבע #d7d7d7 | דף בית | כן

**Comment by OriHoch** [comment]
estimate - 3-5 hours

**Comment by niryariv** [comment]
approved, please implement

**Comment by OriHoch** [comment]
opened subtasks for the specific changes, @niryariv please review:

* remove number of followers element #223 
* organization logo should be aligned to center #224 
* links should not change to white on hover #225 
* change button background colors during hover #226

closing this issue, continue work and communication on the subtasks
