### ISSUE TITLE
בירושלים בלבד, להוסיף קישור משמאל ל״אודות״ 

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#220]
הטקסט  ״[לאתר העיריה](https://www.jerusalem.muni.il/)״, המיקום כאן:

![Screen Shot 2021-05-30 at 13 47 46](https://user-images.githubusercontent.com/1771/120101226-bc41bf00-c14d-11eb-9afb-98750f528c91.png)

עדכן אותי בבקשה אם זה אפשרי וכמה זמן אמור לקחת

**Comment by OriHoch** [comment]
I prefer not to make site specific changes, defined it as a global change based on site settings in this issue: #221
