### ISSUE TITLE
remove number of followers element

### ISSUE THREAD

**Issue by OriHoch** [hasadna/datacity-k8s#223]
**reproduction steps**

go to the following pages:

* dataset page ([example](https://jerusalem.datacity.org.il/dataset/bus-stops))
* organization page ([example](https://jerusalem.datacity.org.il/organization/muni))
* group page ([example](https://jerusalem.datacity.org.il/group/health))

**expected**

* no number of followers component
* on organization / group page - the number of items component will shift to the right
* green "follow" button - TBD if to keep or remove

**actual**

* dataset page:
![image](https://user-images.githubusercontent.com/1198854/120154694-cb317b80-c1f8-11eb-9253-0c2d76a9c158.png)
* organization page:
![image](https://user-images.githubusercontent.com/1198854/120154799-e4d2c300-c1f8-11eb-9dbe-f8b96f7c2145.png)
* group page:
![image](https://user-images.githubusercontent.com/1198854/120154899-fe740a80-c1f8-11eb-99f8-d44036962596.png)

**Comment by OriHoch** [comment]
related to: #219

**Comment by OriHoch** [comment]
@niryariv please approve spec, also, should we keep the green follow button or remove it as well?

**Comment by niryariv** [comment]
approved. also remove the green follow button please.

**Comment by OriHoch** [comment]
deployed
