### ISSUE TITLE
homepage: change button background colors during hover

### ISSUE THREAD

**Issue by OriHoch** [hasadna/datacity-k8s#226]
**reproduction steps**

* go to homepage ([example](https://jerusalem.datacity.org.il/))
* hover over the group icon buttons
* hover over the all dataset items button

**expected**

buttons background color changes to configurable settings in site settings:
* homepage groups inner hover background color (default=d7d7d7)
* homepage datasets button hover background color (default=d7d7d7)

**actual**

button background does not change on hover, no indication that it is a pressable button

**Comment by OriHoch** [comment]
@niryariv please approve spec, I made it configurable because there are different color schemes, so I'm not sure if the same color (d7d7d7) will look good for all sites

**Comment by OriHoch** [comment]
related: #219

**Comment by niryariv** [comment]
approved

**Comment by OriHoch** [comment]
deployed
