### ISSUE TITLE
research for possible solutions to datastore support of xlsx files 

### ISSUE THREAD

**Issue by OriHoch** [hasadna/datacity-k8s#229]
**reproduction steps**

* upload a resource with the following xlsx file: https://kfar-saba.datacity.org.il/dataset/a0a72d56-efeb-4895-b274-ba33f2e08299/resource/2368a4c8-44c0-4dcc-9ec2-c3faecbe7036/download/takziv_2019.xlsx
* check datastore table on resource view page (https://kfar-saba.datacity.org.il/dataset/takziv_ragil/resource/2368a4c8-44c0-4dcc-9ec2-c3faecbe7036)
* edit resource -> datastore tab
* check datastore upload log (https://kfar-saba.datacity.org.il/dataset/takziv_ragil/resource_data/2368a4c8-44c0-4dcc-9ec2-c3faecbe7036)

**expected**

* resource table is shown with valid data
* datastore upload log shows status: completed

**actual**

* resource table is not shown
![image](https://user-images.githubusercontent.com/1198854/120914847-4d161e80-c6a9-11eb-8db6-d77c4f0fc6b1.png)

* datastore upload log shows failure status
![image](https://user-images.githubusercontent.com/1198854/120914876-75058200-c6a9-11eb-8c85-6745f776357a.png)

**notes**

should research for solution to support any kind of xlsx file

**Comment by OriHoch** [comment]
related: #198

**Comment by OriHoch** [comment]
there was a problem with one of the dependencies handling parsing of xlsx files

fixed in https://github.com/hasadna/ckan-cloud-docker/commit/77f9598befecf074e2ab8921f633903ceddee24b

deployed

ran datastore again for the resource, tables is displayed now: https://kfar-saba.datacity.org.il/dataset/takziv_ragil/resource/2368a4c8-44c0-4dcc-9ec2-c3faecbe7036

for other xlsx resources, datastore upload has to manually run again for table to be shown, new xlsx files from now on should be parsed correctly

**Comment by niryariv** [comment]
Thanks!
