### ISSUE TITLE
SSL Errors in datastore upload

### ISSUE THREAD

**Issue by akariv** [hasadna/datacity-k8s#233]
Looks like there's some problem in the ca-certificates on the ckan Docker image perhaps?

https://opendata.hasadna.org.il/dataset/beer-sheva-business-kind-rules

<img width="820" alt="Screen Shot 2021-12-26 at 15 07 57" src="https://user-images.githubusercontent.com/265333/147409151-e6e5a48a-5858-480e-b94b-4fec2f54d621.png">

**Comment by OriHoch** [comment]
fixed: https://github.com/hasadna/ckan-cloud-docker/commit/04c8d81751f6f241f357c021e8566403e236d143

deployed and tested on hasadna instance

the other instances are now being updated as well
