### ISSUE TITLE
homepage layout fixes

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#26]
1.
 לוגו של דאטה-סיטי לצד לוגו העירייה בהדר - להגדיל

2. 
הכותרת - "פורטל מידע פתוח - מעלה אדומים
השם של העירייה צריך להיות בשורה מתחת. בלי מקף

**Comment by maryLoi** [comment]
3.
קרדיט רשות החדשנות

**Comment by maryLoi** [comment]
4.
קישור לגיטהאב ב"אודות"

"קוד האתר זמין תחת רשיון MIT."

**Comment by maryLoi** [comment]
5.
להגדיל פונטים בתפריט, ומתחת לאייקונים - להגדיל ולעשות בולד

**Comment by maryLoi** [comment]
6.

בעברית את המילה "שפה" צריך ליישר לצד ימין של התיבה
![image](https://user-images.githubusercontent.com/8996235/89733472-67b64180-da5e-11ea-997f-d9e1128df660.png)

**Comment by maryLoi** [comment]
7.
האם לשים הגבלה על אורך הרשימות של פריטי המידע?

**Comment by maryLoi** [comment]
8.

![image](https://user-images.githubusercontent.com/8996235/89734011-03957c80-da62-11ea-8aa4-303b334d1495.png)

חפשו מאגר מידע פי מילות מפתח, למשל חינוך או חוגים

**Comment by maryLoi** [comment]
9.
add margins around icons 


![image](https://user-images.githubusercontent.com/8996235/89735886-3a718f80-da6e-11ea-9acb-d895adf05016.png)

if it's too complicated i can fix the icon file - add margins inside the image

**Comment by maryLoi** [comment]
עדכנתי קבצי אייקונים דרך עדכון התחומים, אך הם לא התעדכנו בדף הבית

**Comment by niryariv** [comment]
Mary: fixed
