### ISSUE TITLE
custom colors

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#27]
some of the color configurations through settings dont work

**These work:**
Top header background color
Menu background color
Menu text color
Menu highlight color

**These don't:**
Footer background color
Homepage groups text color
Homepage groups background color
Homepage title text color

**Comment by OriHoch** [comment]
the problem is that there were extra spaces before/after the color

I'll fix it so it ignores extra spaces in https://github.com/hasadna/datacity-k8s/issues/36
