### ISSUE TITLE
אייקונים לא מתעדכנים בעמוד הבית

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#28]
עדכנתי קבצי אייקונים בתוך התחומים, אך הם לא התעדכנו בדף הבית

**Comment by OriHoch** [comment]
deployed

**Comment by maryLoi** [comment]
עדכנתי תחומים, וזה לא התעדכן בדף הבית
(מחקתי את תחום הדת, עדין מופיע בעמוד הראשי)

**Comment by OriHoch** [comment]
עכשיו לא מופיע, כנראה caching
