### ISSUE TITLE
CKAN menus

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#3]
1.
remove header menu: הרשמה, התחברו

2.
להסיר את כל הפריטים בתפריט העליון (מסמכים, ארגונים, ישויות, אודות

3.
remove footer menu:

אודות פורטל מידע - עיריית מעלה אדומים
ממשק המכונה (API) של תביאתה
שיוך CKAN

**Comment by maryLoi** [comment]
Toronto CKAN is a good example
https://open.toronto.ca/catalogue/?sort=last_refreshed%20desc

בתפריט בצד יהיה סינון לפי:
תחומים
תגיות (אפשר כמה רמות של תגיות)
גוף מפרסם
תדירות עדכון
סוג קובץ


On data.gov there's a more detailed drill down into publishers:
Organization Types  
Organizations  
Publishers  
Bureaus  

אנחנו יכולים לעשות למשל:
* אגפים בעירייה
*  גוף מפרסם (עירייה, מתנ"ס א', מתנ"ס ב', תאגיד עירוני וכו')

**Comment by maryLoi** [comment]
בתפריט התחתון אני מציעה שיהיה:

אודות פורטל מידע פתוח
תנאי שימוש
יצירת קשר
קישור לגיטהאב

**Comment by OriHoch** [comment]
@maryLoi 

done + deployed:

Custom site settings can be configured from this URL:

https://maale-adummim.datacity.org.il/settings/edit/settings

Site login/registration is configured to be removed in Maale Adumim instance, so you need to use direct links:

* https://maale-adummim.datacity.org.il/user/login
* https://maale-adummim.datacity.org.il/user/register

About page is configurable from the above settings page using markdown, I currently filled-in some text for hebrew about page. For Arabic / English, if there is no text they show the hebrew about page.

Terms of service and contact us pages can be configured via the settings, you can supply a URL, which could be an external URL, or you can create internal pages uses the pages extension - available in the top header after login. Using the pages extension you can create any page on the site and link to it.
