### ISSUE TITLE
add hasadna logo to footer

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#39]
like [here](http://dados.ufrn.br/):
_______________________________________________________
![image](https://user-images.githubusercontent.com/8996235/89738716-6cd9b780-da83-11ea-8107-250b67505f1a.png)

**Comment by maryLoi** [comment]
**add text:**

פותח על ידי 
[logo hasadna](https://drive.google.com/file/d/1QYS3WDGf49z-JF3RW881g0OggSxqIL4N/view?usp=sharing)
בתמיכה של רשות החדשנות
 [github icon] לקוד האתר.

**Comment by OriHoch** [comment]
deployed

**Comment by maryLoi** [comment]
בפוטר יהיו רק שתי עמודות
העמודה הימנית כמו עכשיו עם כל הקישורים
כל השאר בעמוד ההשמאלית:


פותח על ידי
logo hasadna
בתמיכה של רשות החדשנות
[github icon] לקוד האתר.

מבוסס על מערכת CKAN
בחירת שפה

**Comment by maryLoi** [comment]
add margins above hasadna logo and bellow it

**Comment by maryLoi** [comment]
language selection dropdown - make it narrower, fitted to the word length. it's too wide now

**Comment by OriHoch** [comment]
deployed

**Comment by maryLoi** [comment]
make normal text instead of bold in:
Powered by
Language




![image](https://user-images.githubusercontent.com/8996235/89804177-7bd07080-db3c-11ea-8686-4b9a1a991d28.png)

**Comment by OriHoch** [comment]
deployed
