### ISSUE TITLE
groups and organizations - page design

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#40]
להוריד את הרקע האפור

![image](https://user-images.githubusercontent.com/8996235/89739114-95af7c00-da86-11ea-8f8c-fbf96d8e0f8c.png)

**Comment by maryLoi** [comment]
design like [here](http://data.zagreb.hr/group)

- remove icons
- add light separation line
- add gray underline under the title
- remove veritcal border (right side in English / left side in Hebrew)
- change paragraph text color to #d9d7d6

![image](https://user-images.githubusercontent.com/8996235/89739201-651c1200-da87-11ea-9003-c63569188599.png)


________________________

![Inked89739191-41f16280-da87-11ea-9b8f-980900c5d10d_LI](https://user-images.githubusercontent.com/8996235/89739312-57b35780-da88-11ea-9ad3-1adedc88b585.jpg)

**Comment by maryLoi** [comment]
**עדיפות נמוכה
להוריד את הרקע האפור

![image](https://user-images.githubusercontent.com/8996235/89739473-a01f4500-da89-11ea-9819-da44e76b7e20.png)

**Comment by maryLoi** [comment]
**עדיפות נמוכה
- תגיות צריך לרדת שורה
- להוסיף רווחים לפני כל פילטר (ארגונים, פורמטים וכו')

![image](https://user-images.githubusercontent.com/8996235/89739592-74e92580-da8a-11ea-985e-3b9834370ac3.png)

**Comment by OriHoch** [comment]
opened new issue for line-break between facet name/value: https://github.com/hasadna/datacity-k8s/issues/44

**Comment by OriHoch** [comment]
deployed
