### ISSUE TITLE
doc=docx

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#41]
מבחינת סינון לפי פורמטים לא צריך להפריד בין שתי סיומות אלה

![image](https://user-images.githubusercontent.com/8996235/89739665-49b30600-da8b-11ea-98cd-2c1d4176fe25.png)

**Comment by OriHoch** [comment]
this might be difficult to do, also the separation can be useful for developers, I suggest to put it at lower priority
