### ISSUE TITLE
image size

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#42]
what is the size of the image bar?

**Comment by OriHoch** [comment]
what is the image bar?

**Comment by maryLoi** [comment]
תמונת הרקע הגדולה

**Comment by OriHoch** [comment]
current image size is 4917 X 1500

https://www.datacity.org.il/wp-content/uploads/2020/08/zagreb.png

**Comment by akariv** [comment]
This size is too big for any practical use...
width should be around 1200px imo, e.g. 1208 x 368 (keeping the same
proportions)

**Comment by OriHoch** [comment]
I'm not sure how this css works, there are screens with much larger resolution today and also devices with retina display which might show cropped image if resolution is too low

**Comment by akariv** [comment]
We can set in the css that the image should fit the object its size and not
get cropped.
4000px is too much both from a performance point of view (time to load) and
from a practical point of view (the human eye can't see such minute
details, even with retina displays).

**Comment by niryariv** [comment]
@akariv @OriHoch status? We need this in order to tell the designers what size image is needed

**Comment by OriHoch** [comment]
this is the image that's used in [Maale Adummim](https://maale-adummim.datacity.org.il/) - 2560x874
https://www.datacity.org.il/wp-content/uploads/2020/09/Maale_Adumim_panorama_2-scaled.jpg

**Comment by niryariv** [comment]
@niryariv - check image size best practices w/ designer
