### ISSUE TITLE
Sharing image URL

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#46]
כאשר שמים בשדה זה קישור לתמונה, התמונה לא מתעדכנת בדף הראשי

למשל הסמל של העירייה
https://www.datacity.org.il/wp-content/uploads/2020/08/Untitled.png

**Comment by OriHoch** [comment]
this field sets the image for sharing - which is displayed on facebook / whatsapp, etc.. it should be a different image then the image logo displayed on the site, and should be according to the help text displayed under this field

the logo which is displayed on the header is set from the normal ckan settings (the "hammer" icon in the top menu) - under תצורה - לוגו האתר
