### ISSUE TITLE
responsivity

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#48]
horizontally scrollable-
 כשהאתר נטען יש רווח מצד שמאל בין התמונה לקצה של החלון. אין ממש סקרול-בר, אבל ניתן להזזה מצד לצד

**Comment by maryLoi** [comment]
כל האייקונים עולים אחד על השני

**Comment by maryLoi** [comment]
בדף ארגון ובדף תחום האייקון ענק

**Comment by maryLoi** [comment]
breadcrumbs don't show on mobile

![image](https://user-images.githubusercontent.com/8996235/89910182-99631000-dbf8-11ea-9abd-07a54e258ff7.png)

**Comment by OriHoch** [comment]
@maryLoi 

following bugs do not reproduce / not clear where they happen, please write which device this occurs on + add a screenshot showing the bug:

> horizontally scrollable-
> כשהאתר נטען יש רווח מצד שמאל בין התמונה לקצה של החלון. אין ממש סקרול-בר, אבל ניתן להזזה מצד לצד

> כל האייקונים עולים אחד על השני

**Comment by OriHoch** [comment]
following bugs were fixed + deployed:

> בדף ארגון ובדף תחום האייקון ענק

> breadcrumbs don't show on mobile

**Comment by niryariv** [comment]
fixed (add horizontal scrolling issue separately)
