### ISSUE TITLE
רקע מתחת לכותרת בדף הבית

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#52]
להוסיף מלבן לבן מתחת לכותרת הראשית

<img width="1589" alt="Screen Shot 2020-08-11 at 12 45 15" src="https://user-images.githubusercontent.com/8996235/90330830-78177080-dfb8-11ea-962b-2e9d23be2cc6.png">

**Comment by OriHoch** [comment]
deployed
