### ISSUE TITLE
לסדר אייקונים של תחומים ב-3 שורות

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#53]
בדף הראשי

**Comment by OriHoch** [comment]
@maryLoi currently there are 10 groups, this doesn't divide by 3, how will this work?
how many icons in each row?

**Comment by maryLoi** [comment]
כן, אני אחזיר את ה"דת" שהורדתי ואמציא עוד אחד כדי שיהיה 12
@OriHoch

**Comment by OriHoch** [comment]
deployed
