### ISSUE TITLE
WP - make toggle right-to-left

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#55]
toggle element in WP
the buttons should be on the right
all text everywhere should be right-to-left

![image](https://user-images.githubusercontent.com/8996235/90335932-00117080-dfe1-11ea-9b62-9b9b41d4d36c.png)

**Comment by OriHoch** [comment]
@maryLoi did you mean that the toggle buttons should be on the left?

**Comment by OriHoch** [comment]
@maryLoi where is this page? please add a link to it

**Comment by niryariv** [comment]
Mary: no longer relevant. Closing
