### ISSUE TITLE
WP - stylish bullet list

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#56]
I would like global style for bullet list:
- custom bullet shapes
- colored bullet shapes
- custom size bullets
- whole list aligned rtl

something like this (i will experiment with other colors and shapes later)

![image](https://user-images.githubusercontent.com/8996235/90511003-873b2180-e164-11ea-8070-03ed8d1ece69.png)

**Comment by OriHoch** [comment]
I fixed the list rtl, regarding providing interface to modify and experiment with list styles, its' out of scope of this project

Please let me know which style you want and I will implement it. if there is existing HTML showing this style, add a link to that style and I'll copy from there. For custom bullet shape I will need the image of this bullet

**Comment by niryariv** [comment]
@maryLoi

**Comment by niryariv** [comment]
closing for now
