### ISSUE TITLE
WP - site preview

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#57]
change site preview to show the logo image

![image](https://user-images.githubusercontent.com/8996235/90539127-1c9bdd00-e188-11ea-98dd-e8c5f7556932.png)

**Comment by OriHoch** [comment]
fixed + deployed

**Comment by maryLoi** [comment]
@OriHoch 
איפה משנים את התמונה?

**Comment by OriHoch** [comment]
it's not configurable, send me the image logo you want to use
