### ISSUE TITLE
מיפוי מאגרים מעלה אדומים

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#6]
List:

https://maaleadummim-my.sharepoint.com/:x:/g/personal/gadi_mam_org_il/EWjkqZ2IBRpJo1XQCVgFN8EBzyP9ewSC768p97C5W6bkSw?e=4%3AMDcyES&at=9

Files:

https://maaleadummim-my.sharepoint.com/:f:/g/personal/gadi_mam_org_il/EuanjijoqyNBsOglBi-7kcYBC4D0nftUCJr9-F1XNjByqw?e=5%3ahZs50A&at=9

**Comment by maryLoi** [comment]
Should we upload all files in the folder? or ask them to get in a better format?

Some files are in horrible formats. Which of them should they bother to get in an alternative format?

Examples:
- "רצף מענים"
- "תנועות נוער"

**Comment by maryLoi** [comment]
Upload everything. 
Next step prioritize and clean

**Comment by niryariv** [comment]
הוחלט שהדברים יעלו כמו שהם, סוגר
