### ISSUE TITLE
Deleted group, is not fully deleted

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#60]
תחום שמוחקים, לא נמחק בפועל והדומיין נשאר תפוס

למשל מחקתי את תחום הדת. אבל כשבאתי ליצור אותו מחדש לא ניתן היה להשתמש באותה כתובת עבורו. לכן נאלתי לקרוא לו 
**religion2**
https://maale-adummim.datacity.org.il/group/religion2

עדין ניתן לגשת לתחום המחוק דרך עדכוני פעילות של המשתמש
https://maale-adummim.datacity.org.il/group/religion

**Comment by OriHoch** [comment]
רק משתמשים מחוברים עם הרשאות יכולים לראות תחום שנמחק

ניתן לשנות את המזהה של התחום הנמחק ולאחר מכן אפשר לתת לתחום חדש את המזהה שלו

זה מה שעשיתי עבור דת:

* התחום שנמחק: https://maale-adummim.datacity.org.il/group/edit/religion-old
* התחום החדש: https://maale-adummim.datacity.org.il/group/edit/religion

נראה לי שעדיף לא להשקיע בתיקון הבאג בגלל שמדובר במקרה קצה שיש לו פתרון קל לביצוע ע"י המשתמשים
