### ISSUE TITLE
Downloading file name

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#61]
When downloading file, the default name in the Save dialog appear as "-"

Example:
https://maale-adummim.datacity.org.il/dataset/special-kindergardens/resource/5cf97bf7-3877-426b-821b-7a64b34d7b99

click the link and try to save

should be the original filename
גני ילדים חינוך מיוחד.xlsx

**Comment by OriHoch** [comment]
we discussed this and decided not to fix it in #47

**Comment by maryLoi** [comment]
זה לא בדיוק אותו מקרה. 
במקרה של שמירת קובץ המשתמש הרגיל הולך להתקל הרבה יותר מאשר במקרה של עריכת קובץ, לכן כאן זה נראה לי יותר משמעותי.

זה ממש מסובך לסדר?

**Comment by OriHoch** [comment]
כן, דיברנו על זה, לפי דעתי סיכמנו שנדריך את מי שמעלה קבצים להעלות עם שמות קבצים באנגלית

**Comment by niryariv** [comment]
wontfix (for now)
