### ISSUE TITLE
לבטל כותרות בטבלת מידע נוסף בפריט

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#62]
לא להציג את שמות העמודות
שדה, ערך
![image](https://user-images.githubusercontent.com/8996235/91967517-052e2980-ed1c-11ea-8427-12049c91e7f3.png)

**Comment by OriHoch** [comment]
we discussed and decided not to do it in this issue: https://github.com/hasadna/datacity-k8s/issues/34

**Comment by niryariv** [comment]
wontfix
