### ISSUE TITLE
Icon for Datasets that hold URL

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#63]
פריט מידע שהוא קישור - לא מופיע לו אייקון עם סוג הקובץ כמו באקסל או בוורד

![image](https://user-images.githubusercontent.com/8996235/91967794-61914900-ed1c-11ea-951d-70d37ac7200b.png)

**Comment by OriHoch** [comment]
הלינק בפריט של ארגוני התנדבות הוא ללא סיומת לכן אין דרך לדעת איזה אייקון אמור להופיע

ניתן לבחור את הפורמט באמצעות שדה פורמט, כרגע הזנתי שם
"Web"
