### ISSUE TITLE
תרגום לערבית

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#66]
לייצר תרגום לערבית למעטפת של הפורטל, ולדף אודות

להשלים תרגום לאנגלית לשמות התחומים

**Comment by maryLoi** [comment]
אודות
תחומים
דאטה-סטים

סטרינגים דינאמיים

גם לאנגלית וגם לערבית
אישיו לפיתוח

**Comment by niryariv** [comment]
@maryLoi  זה פעיל? יש לזה צורך כרגע בפרויקט ספציפי?

**Comment by niryariv** [comment]
@maryLoi can u add the transifex link?

**Comment by maryLoi** [comment]
https://www.transifex.com/the-public-knowledge-workshop/datacity-ckan/dashboard/
