### ISSUE TITLE
איך הופכים כתובת למפה?

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#67]
אם יש אקסל עם כתובות, כמו למשל במעלה אדומים יש כתובות ברשימת הספריות, וגם גני ילדים.
איך אפשר לייצר תצוגה של מפה בפורטל?

**Comment by OriHoch** [comment]
אין אפשרות כזאת

**Comment by maryLoi** [comment]
אז מאיזה סוג של קבצים אפשר לייצר ויו של מפה? אפשר להמיר את הקובץ ידנית לפורמט כזה?
@OriHoch

**Comment by OriHoch** [comment]
אני לא מכיר דרך להמיר ידנית
יש פורמטים סטנדרטיים לתצוגת מפה, לפי דעתי הכי נפוץ זה
geojson

**Comment by niryariv** [comment]
@maryLoi 
באיזה הקשר השאלה? הטיקט עדיין רלבנטי?

**Comment by niryariv** [comment]
might handle in the new mapping feature
