### ISSUE TITLE
default values for dataset

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#68]
ערכי ברירת מחדל:

גרסה - 1.0

פומבי במקום פרטי

**Comment by maryLoi** [comment]
האם ניתן להסתיר שדות ללא ערכים בפריט מידע ובקובץ?

**Comment by niryariv** [comment]
@OriHoch status?

**Comment by maryLoi** [comment]
רשיון השימוש: ODbL

**Comment by OriHoch** [comment]
will try to do it next week

**Comment by OriHoch** [comment]
regarding hiding fields without values - where exactly should these fields be hidden? In any case I thinks this is probably hard to do and not worth the effort

**Comment by OriHoch** [comment]
deployed
