### ISSUE TITLE
הגדרות עיצוב

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#69]
כדי להעביר לך הגדרות לעיצוב עבור הפורטל, איך אתה מעדיף לקבל אותם מהמעצבת?

- בפרמטרים מוגדרים - למשל גדלים ורווחים בפיקסלים מדוייקים

- או בסקיצה ויזואלית, שתממש אחכ בקוד?

**Comment by OriHoch** [comment]
זה תלוי באיזה עיצוב מדובר, כדאי לעבוד בשיתוף פעולה איתה ולהבין מה בדיוק מעצבים

**Comment by maryLoi** [comment]
שאני אקבע לנו שיחה איתה?
היא יכולה בערב רק. יכול להסתדר לך ב-19:00 או אחרי?

**Comment by niryariv** [comment]
@maryLoi אני מניח שאפשר לסגור את זה?

**Comment by niryariv** [comment]
understand from @maryLoi that Ori & the designers had a discussion and figured it out. closing
