### ISSUE TITLE
easy translation editing

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#7]
make translation editing easy

**Comment by maryLoi** [comment]
Ori will develop a tool for local translation

**Comment by OriHoch** [comment]
@maryLoi invited you to Transifex datacity team, the project is `datacity-ckan`

I translated groups to `תחומים` to make sure it works

After you make translations you need to let me know to update it on the site

**Comment by maryLoi** [comment]
צריך לעדכן אותך לגבי כל סטרינג או באופן כללי?

בכל מקרה תרגמתי מלא מחרוזות היום

**Comment by OriHoch** [comment]
it's updated now, next time, please open an issue after you finish updating translations and write a summary of the changes you did so we can deploy and test it
