### ISSUE TITLE
New CKAN

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#70]
צריך להרים 2 פורטלים נוספים:
1. לוד
2. ראשל"צ

**Comment by niryariv** [comment]
@maryLoi תוכלי בבקשה לתת קצת פרטים - איפה אנחנו עומדים מול הרשויות האלו?

**Comment by niryariv** [comment]
currently on hold until we move forward with these munis

**Comment by niryariv** [comment]
סוגר, נפתח טיקט פר רשות כשיהיה רלבנטי
