### ISSUE TITLE
WP - Elementor layout

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#72]
בדף "פרסום מידע" אני מנסה לסדר את הרוחב של הטקסט כפי שמוצג במובייל
כרגע ניסיתי לשחק עם כל ההגדרות שיש, וחיפשתי מלא בגוגל, ואני פשוט לא מצליחה להגדיל את רוחב הטקסט במקטעים של "אשכולות מידע" ו-"פרסום מידע". ניסיתי לגעת בהגדרות של מארג'ין ופדינג גם של סקשן, גם של עמודה וגם של תיבת הטקסט. לא עוזר.

מה שכן, המקטעים של האשכולות הם כן יותר רחבים. בדקתי שם בכל ההגדרות הכל דיפולטי. גם ניסיתי לעשות קופי פייסט של סטייל (יש פיצ'ר של להעתיק סטייל בין אלמנטים), גם לא השפיע

![image](https://user-images.githubusercontent.com/8996235/93214334-b77add80-f76d-11ea-91d9-fdaba2acbfba.png)

![image](https://user-images.githubusercontent.com/8996235/93214508-f01ab700-f76d-11ea-9374-ed57cc8f280f.png)

**Comment by niryariv** [comment]
fixed according to @maryLoi
