### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#77]
When logged in as Admin In Maale Adumim [site](https://maale-adummim.datacity.org.il/he/), using Firefox 81 on OS X Catalina, can scroll about 6-7 screenfulls to the side, far beyond the content.

Does not happen in Chrome or when not logged in.

![Screen Shot 2020-10-08 at 21 00 32](https://user-images.githubusercontent.com/1771/95496440-86c34800-09a9-11eb-841b-d22af6ad795e.png)

**Comment by akariv** [comment]
duplicate of #17 ...

**Comment by niryariv** [comment]
yep.. closing
