### ISSUE TITLE
בדיקת נגישות לאתר הקיים של מעלה אדומים

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#79]
https://maale-adummim.datacity.org.il/

צריך לעבור על האתר ולבדוק אותו מבחינת עמידה בתקני נגישות

**Comment by eilanabenish** [comment]
בחלק העליון במסך יש אייקונים שהם קישורים ריקים 
אייקון הקישור לניהול הגדרות משתמש, ניהול דפים ותמונת האייקון ליד השם של האדמין.
צריך להגדיר לקישורים טקסט בדומה לזה שיש לאייקון המנהל.
ראו SC 1.3.3 Sensory Characteristics
https://www.w3.org/WAI/WCAG21/quickref/#sensory-characteristics

**Comment by eilanabenish** [comment]
חיפוש באתר
לכפתור החיפוש אין תווית
יש להוסיף תווית שתיקרא "חפש"
SC 2.4.6 [Headings and Labels AA
https://www.w3.org/WAI/WCAG21/quickref/#headings-and-labels

**Comment by eilanabenish** [comment]
לתמונות הקישור באזור התפריט העליון אין טקסט   חלופיכך שקורא מסך מזהה אותו כ banner landmark    Maale Adummim Data Portal  graphic    visited  link  
גם לתמונת הקישור של לוגו הסדנא 
לכל התמונות ותמונות הקישור יש לספק טקסט חלופי תקין ב ALT
תמונות קישוט ניתן להגדיר כ ALT ריק
SC 1.1.1 Non-text Content A
https://www.w3.org/WAI/WCAG21/quickref/#non-text-content

**Comment by eilanabenish** [comment]
תפריט בחירת שפה בפוטר
צריך להגדיר לפקד תווית שתיקרא למשל "בחירת שפה"

SC 2.4.6 [Headings and Labels AA
https://www.w3.org/WAI/WCAG21/quickref/#headings-and-labels

**Comment by eilanabenish** [comment]
תפריט בחירת שפה בפוטר
צריך להגדיר לפקד תווית שתיקרא למשל "בחירת שפה"

SC 2.4.6 [Headings and Labels AA
https://www.w3.org/WAI/WCAG21/quickref/#headings-and-labelsמנגנון דילוג לתוכן מרכזי
בכל אתר אינטרנט צריך שיהיה מנגנון דילוג לתוכן מרכזי בעמוד.
זהו קישור ראשון באתר שנקרא "דלג לתוכן מרכזי" ולחיצה עליו מאפשרת למשתמשי מקלדת עם וללא קורא מסך להגיע ישירות לאזור תוכן מרכזי בעמוד מבלי לעבור על כל מנגנוני הניווט החוזרים על עצמם בסדרת דפי האינטרנט באתר.
הקישור יכול להיות מוסתר,  ונהפך לגלוי רק בעת ניווט מקלדת עם וללא קורא מסך.
למשתמשי מקלדת ללא קורא מסך, המנגנון הזה חיוני ביותר משתי סיבות: 1 אנשים רבים עם מוגבלות מוטורית בידיים חווים לעיתים כאבים פיזיים בעת ניווט בממשקי משתמש ומטרת המנגנון היא להקל עליהם בזמן ניווט. שנית, למשתמשי מקלדת ללא קורא מסך אין את האפשרות לנווט בין כותרות באמצעות מקשי קיצור  במקלדת בדומה למשתמשי תוכנות קוראות מסך שיכולים לעבור בין כותרות.
באתר מעלה אדומים, קיים קישור של דילוג לתוכן מרכזי אך הוא אינו נראה ולא ניתן למעשה לגשת אליו באמצעות טכנולוגיה מסייעת.
את הקישור גיליתי לאחר שביקשתי ממוחמד סולימן להפיק עבורי קובץ של כל הקישורים באתר ורק אז גיליתי אותו.
לפיכך, יש  להגדיר שהקישור הזה יהיה זמין לכל משתמשי המקלדת.
ראו SC 2.4.1 Bypass Blocks A
https://www.w3.org/WAI/WCAG21/quickref/#bypass-blocks

**Comment by eilanabenish** [comment]
עיצוב נגיש: ריכזתי בקובץ מצורף שמשולבים בו צילומי מסך והסברים את בעיות הנגישות בתחום של עיצוב נגיש
[בדיקת עיצוב נגיש  פורטל מאגרי מידע מעלה אדומים.docx](https://github.com/hasadna/datacity-k8s/files/5370683/default.docx)

**Comment by niryariv** [comment]
הדוח מעולה. העליתי אותו לדרייב של הפרויקט, [כאן](https://docs.google.com/document/d/1Ch_7ZxgWKC0WKRftFoMB3h2TKbuzagSjNOStHDZmGrk/edit?usp=sharing)

@eilanabenish יוצר איתך קשר לגבי הפיכה שלו למשימות

**Comment by eilanabenish** [comment]
עדיין לא סיימתי עם דוח הנגישות - זה יקרה ביום שני. ניר עדכנתי אותך גם בווצאפ

**Comment by niryariv** [comment]
@eilanabenish סיימת את הדוח ויצירת המשימות? אפשר לסגור את המשימה?
