### ISSUE TITLE
document types

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#8]
ראיתי פורטלים עירוניים שמכילים לא רק דאטה-סטים, אלא גם מסמכים, ניירות מדיניות, ועוד סוגים של פריטים
אולי כמו ב"יודעת
האם נרצאה גם אנחנו לאפשר מסמכים שונים?

**Comment by akariv** [comment]
Related to #10

**Comment by niryariv** [comment]
מבין ממרי שהיה דיון אם לייצר תחום ספציפי למסמכים כאלו, והוחלט שלא. מן הסתם הרשות יכולה להעלות כל מסמך שהיא רוצה בכל במקרה
