### ISSUE TITLE
טקסט חלופי לתמונות ותמונות קישור

### ISSUE THREAD

**Issue by eilanabenish** [hasadna/datacity-k8s#84]
בדף הבית של [מעלה אדומים](https://maale-adummim.datacity.org.il) לתמונות הקישור של התחברות ותמונות הלוגו של מעלה אדומים והסדנא איןבפוטר  טקסט חלופי ברור.

![image](https://user-images.githubusercontent.com/38149556/96577680-a416e100-12dc-11eb-9a29-6ff51615c515.png)

![image](https://user-images.githubusercontent.com/38149556/96577839-ef30f400-12dc-11eb-8fe6-c2a82e1959fc.png)

![image](https://user-images.githubusercontent.com/38149556/96578197-77af9480-12dd-11eb-9af5-13ca1c03abf4.png)

לכל התמונות ותמונות הקישור כמו גם לאייקונים, יש לספק טקסט חלופי שיתאר את מטרת התמונה בקצרה. תמונות קישוט שאין להם שום פונקציונליות והם משמשים כרקע בלבד, ניתן להגדיר עם ALT ריק.

[WCAG 2.0 SC  1.1.1 Non-text Content A](https://www.w3.org/WAI/WCAG21/quickref/#non-text-content)

**Comment by OriHoch** [comment]
צריך לאפיין

**Comment by niryariv** [comment]
אפיון:

להוסיף לתמונות לעיל תגית alt:

״לוגו מעלה אדומים״

״לוגו דאטה סיטי״

״לוגו הסדנא לידע ציבורי״

**Comment by OriHoch** [comment]
נקודתית רק באתר מעלה אדומים? אם בכל האתרים אז לפי איזה לוגיקה מחליטים מה יהיה הטקסט של לוגו מעלה אדומים?

**Comment by niryariv** [comment]
בשלב זה נשנה את הטקסט ל״לוגו רשות מקומית״. שם הרשות מופיע ממילא בטקסט במקומות אחרים.

בשלב מאוחר יותר, אם יגיע, יהיה שדה של ״שם הרשות״ בהגדרות שממנו ייגזרו אוטומטית (עם אפשרות לשינוי ע״י המשתמש) תכנים שהיום מוגדרים בשדות כמו ״סלוגן האתר״, ״כותרת פורטל״, site title hebrew ואחרים

**Comment by OriHoch** [comment]
deployed
