### ISSUE TITLE
ייבוא מידע אוטומטי

### ISSUE THREAD

**Issue by niryariv** [hasadna/datacity-k8s#85]
אנחנו רוצים לבדוק יכולת לייבא מידע אוטומטית, כדי שנוכל להקים אתר חדש לרשות עם מידע רלבנטי כבר בתוכו. למרות שהמידע כבר זמין ברמה הארצית אנחנו מניחים שמשתמשים רבים לא מכירים מקורות כמו דאטה.גוב או מתקשים למצוא בהם את המידע שהם מחפשים, כך שיש ערך אמיתי בהנגשה שלו בהקשר של אתר רשות מקומית.

 סימונה ואני יוצרים קובץ של מידע מדטה.גוב ומקורות אחרים שיכול להיות מעניין לרשות מקומית, [כאן](https://docs.google.com/spreadsheets/d/1VpnSTMZFLBjCzLLhxZ3av7ZOWdtvbZ2ySs-cQ8IgLCc/edit#gid=0)

בשלב זה נתייחס רק למקורות מידע שנתנו להם ציון ״ערך לתושב״ 5

המשימה היא:
1. לקרוא את הקובץ המקושר מדאטה.גוב  
2. לגזור ממנו את המידע שרלבנטי לרשות מקומית ספציפית אל תוך קובץ משלה
3. לייבא את הקובץ החדש אל פורטל הרשות המקומית

תוכלו לתת הערכה לגבי זמן פיתוח נדרש?

**Comment by akariv** [comment]
@niryariv
מאמין שמדובר ביום-יומיים עבודה, בהנתן ש @OriHoch סיים להרים את שרת ה-dgp בקלאסטר.
אם אפשר להוסיף לטבלה כיצד אפשר לסנן את השורות של הרשות המקומית הרלוונטית מתוך הקובץ (לפי שם, סמל, או בצורה אחרת) זה יהיה מצוין.

**Comment by OriHoch** [comment]
כן, זה דומה למה שאני עושה עכשיו עבור #59
