### ISSUE TITLE
חסרה תווית לכפתור חיפוש

### ISSUE THREAD

**Issue by eilanabenish** [hasadna/datacity-k8s#86]
לצד שדה החיפוש יש כפתור חיפוש והוא ללא תווית
התווית לכפתור צריכה להיות - חפש או חיפוש 
![כפתור חיפוש ללא תווית](https://user-images.githubusercontent.com/38149556/96683116-62407600-1382-11eb-8e5d-04f60e75d84c.png)

[WCAG 2.0 SC 2.4.6 Headings and Labels Level AA](https://www.w3.org/WAI/WCAG21/quickref/#headings-and-labels)

**Comment by OriHoch** [comment]
הערכה - שעת פיתוח

**Comment by OriHoch** [comment]
not clear what exactly needs to be done, what is meant by "תווית"?

**Comment by niryariv** [comment]
להחליף את 
`<button type="submit">`
ב 
`<button type="submit" aria-label="חיפוש">`

**Comment by OriHoch** [comment]
deployed
