### ISSUE TITLE
תווית חסרה לפקד בחירת שפה בפוטר

### ISSUE THREAD

**Issue by eilanabenish** [hasadna/datacity-k8s#87]
בפוטר יש תפריט שפה. הפקד ללא תווית כך שקורא מסך מזהה אותו כך: content info landmark    clickable  menu button  subMenu  editable  
ולכן לא ברור מה ניתן לבחור בתפריט הזה שכולל תפריט משנה.
לכן יש לספק תווית לפקד זה
![פקד בחירת שפה ללא תווית](https://user-images.githubusercontent.com/38149556/96684476-505fd280-1384-11eb-866e-ea174a3c686d.png)

**Comment by niryariv** [comment]
https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Text_labels_and_names#use_label_attribute_on_optgroup_elements

**Comment by OriHoch** [comment]
הערכה - שעת פיתוח

**Comment by OriHoch** [comment]
there already is a label as specified in the link you sent - 
![image](https://user-images.githubusercontent.com/1198854/112137501-03a15180-8bd9-11eb-8291-e8bfb1dfbdc6.png)

**Comment by niryariv** [comment]
@eilanabenish תוכלי לפרט בבקשה מה צריך לשנות בקוד לעיל?

**Comment by eilanabenish** [comment]
לפקד הזה אין תווית עם שם שניתן לזיהוי על ידי קורא מסך
לכן הוא מוקרא כ menu button subMenu editable
השם צריך להיות בחר שפה 
menu button= בחר שפה

**Comment by niryariv** [comment]
@eilanabenish תוכלי לפרט ספציפית מה צריך לשנות בקוד?

**Comment by niryariv** [comment]
@OriHoch תוריד בבקשה את רכיב השפה בשלב זה

**Comment by OriHoch** [comment]
done, deployed
