### ISSUE TITLE
ניראות מוקד המקלדת

### ISSUE THREAD

**Issue by eilanabenish** [hasadna/datacity-k8s#88]
הסבר: אנשים רבים עם מוגבלות מוטורית בידיים משתמשים במקלדת לצורך ניווט בממשק המשתמש. במונח מקלדת הכוונה למקלדת סטנדרטית, מקלדות מותאמות לגודל כף יד שונה, מתגים ואמצעי ניווט נוספים המשמשים מגוון רחב של אנשים עם סוגים שונים של מוגבלות מוטורית בידיים.
לדוגמה, במקלדת סטנדרטית, לחיצה על מקש ה TAB להתקדמות קדימה או Shift + Tab לחזרה אחורה,  מעבירה את מוקד המקלדת בין פקדים אינטראקטיביים כגון קישורים ופקדי טפסים.
בכדי שניתן יהיה לראות בכל רגע נתון היכן נמצא מוקד המקלדת ללא עכבר, על כל מרכיב אינטראקטיבי כגון קישורים ופקדי טפסים לקבל אפקט ויזואלי שונה ביחס למרכיבים שאינם במוקד המקלדת.
חשוב להבהיר כי האפקט  הויזואלי צריך לחול רק כשמרכיב אינטראקטיבי מקבל פוקוס מקלדת כך שלמעשה הוא מוסתר עד שמשתמש מקלדת עושה שימוש בממשק באמצעות מקלדת בלבד.
באתר מעלה אדומים יש באזור התוכן המרכזי  תחת הכותרת חפשו מידע לפי תחומים קישורים לקטגוריות שונות. האפקט  הוויזואלי שם למרכיבים אינטראקטיביים במוקד המקלדת כמעט ובלתי נראה גם לאדם שראייתו תקינה.
בתמונה שלהלן, נסו לזהות את הקישור שנמצא במוקד המקלדת 

נסו לזהות כמה שיותר מהר היכן נמצא מוקד המקלדת
![היכן נמצא מוקד המקלדת](https://user-images.githubusercontent.com/38149556/96685651-14c60800-1386-11eb-84f7-03895b4b8a75.png)

שתי דוגמאות טובות לניראות  מוקד המקלדת
בקישורים תחת הכותרת פריטי מידע פופולריים  מוקד המקלדת הרבה יותר טוב ובולט
![בקישורים תחת הכותרת פריטי מידע פופולריים  מוקד המקלדת הרבה יותר טוב ובולט
](https://user-images.githubusercontent.com/38149556/96685821-52c32c00-1386-11eb-92cf-8abc1bfa1e47.png)

דווקא האפקט הוויזואלי המתקבל בריחוף עכבר מצוין ואני מקווה שיש דרך להחיל אותו גם לגבי ניווט מקלדת – לדוגמה

![אפקט ויזואלי טוב בריחוף עכבר על קישורים](https://user-images.githubusercontent.com/38149556/96686154-d715af00-1386-11eb-99d2-21290fe72714.png)

[WCAG 2.0 SC 2.4.7 Focus Visible Level AA](https://www.w3.org/WAI/WCAG21/quickref/#focus-visible)

**Comment by OriHoch** [comment]
צריך לאפיין

**Comment by niryariv** [comment]
אפיון:

add `tabindex="0"` to all the category buttons' `<div>` elements:

![Screen Shot 2021-03-22 at 10 41 13](https://user-images.githubusercontent.com/1771/111962572-21988480-8afb-11eb-91db-e553b26eab74.png)

**Comment by OriHoch** [comment]
deployed
