### ISSUE TITLE
publisher hierarchy

### ISSUE THREAD

**Issue by maryLoi** [hasadna/datacity-k8s#9]
לבדוק האם יש דרך לייצר היררכיה של ארגונים, ומחלקות בתוך הארגונים. למשל עירייה, ותחתיה יש אגפים שונים. מתנ"ס ותחתיו יש מחלקות שונות, וכו?

**Comment by maryLoi** [comment]
On [data.gov](https://catalog.data.gov/dataset) it seems to be flat

![image](https://user-images.githubusercontent.com/8996235/88485511-ec915d80-cf7e-11ea-914d-0efbeb37effd.png)

**Comment by OriHoch** [comment]
https://github.com/ckan/ckanext-hierarchy/blob/master/README.md#ckanext-hierarchy---organization-hierarchy-for-ckan

**Comment by akariv** [comment]
I think this should be a WONTFIX
